hrp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#import notify
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^leave/', include('leave.urls', namespace='leave')),
    url(r'^appraisal/', include('appraisal.urls', namespace='appraisal')),
    url(r'^recruitment/', include('recruitment.urls', namespace='recruitment')),
    url(r'^asset/', include('asset.urls', namespace='asset')),
    url(r'session_security/', include('session_security.urls')),
#    url(r"^notifications/", include("pinax.notifications.urls",
#        namespace="pinax_notifications")),
    url(r'^notifications/', include('notify.urls', 'notifications')),
    url(r'^', include('payroll.urls', namespace='payroll')),
]

leave/urls.py
__author__ = "Steven Kawuma <kawuma@gmail.com>"
__date__ = "Feb 14, 2017 3:06:12 PM"

from django.conf.urls import url
from leave.views import *

urlpatterns = [

    url('^holiday/new/$', HolidayCreateView.as_view(), name='holiday_create'),
    url('^holiday/$', HolidayListView.as_view(), name='holiday_list'),
    url('^holiday/page(?P<page>\d+)/$', HolidayListView.as_view(),
        name='holiday_list_p'),    
    url('^holiday/edit/(?P<pk>\d+)/$', HolidayUpdateView.as_view(), 
        name='holiday_edit'),
    url('^holiday/delete/(?P<pk>\d+)/$', HolidayDeleteView.as_view(), 
        name='holiday_delete'),
        
    url('^lperiod/new/$', LeavePeriodCreateView.as_view(), 
        name='leave_period_create'),
    url('^lperiod/$', LeavePeriodListView.as_view(), name='leave_period_list'),
    url('^lperiod/page(?P<page>\d+)/$', LeavePeriodListView.as_view(),
        name='leave_period_list_p'),    
    url('^lperiod/edit/(?P<pk>\d+)/$', LeavePeriodUpdateView.as_view(), 
        name='leave_period_edit'),
    url('^lperiod/delete/(?P<pk>\d+)/$', LeavePeriodDeleteView.as_view(), 
        name='leave_period_delete'),

    url('^ltype/new/$', LeaveTypeCreateView.as_view(), 
        name='leave_type_create'),
    url('^ltype/$', LeaveTypeListView.as_view(), name='leave_type_list'),
    url('^ltype/page(?P<page>\d+)/$', LeaveTypeListView.as_view(),
        name='leave_type_list_p'),    
    url('^ltype/edit/(?P<pk>\d+)/$', LeaveTypeUpdateView.as_view(), 
        name='leave_type_edit'),
    url('^ltype/delete/(?P<pk>\d+)/$', LeaveTypeDeleteView.as_view(), 
        name='leave_type_delete'),

    url('^lapprover/$', LeaveApproverView.as_view(), name='leave_approvers'),
    url('^lapprover/(?P<rem_pk>\d+)/rem/$', LeaveApproverView.as_view(), 
        name='leave_approver_remove'),

    url('^lrequest/$', LeaveRequestListView.as_view(), 
        name='leave_request_list'),
    url('^lrequest/(?P<cat>[P|A|E|C|D]+)/$', LeaveRequestListView.as_view(), 
        name='leave_request_list_f'),
    url('^lrequest/(?P<cat>[P|A|E|C|D]+)/page(?P<page>\d+)/$', LeaveRequestListView.as_view(), 
        name='leave_request_list_f_p'),
    url('^lrequest/page(?P<page>\d+)/$', LeaveRequestListView.as_view(),
        name='leave_request_list_p'),    
    url('^lrequest/(?P<cancel_pk>\d+)/cancel/$', LeaveRequestListView.as_view(), 
        name='leave_request_cancel'),
    url('^lrequest/new/$', LeaveRequestCreateView.as_view(), 
        name='leave_request_create'),

    url('^larequest/$', LeaveApplicationListView.as_view(), 
        name='leave_application_list'),
    url('^larequest/(?P<cat>[P|A|E|C|D]+)/$', LeaveApplicationListView.as_view(), 
        name='leave_application_list_f'),
    url('^larequest/(?P<cat>[P|A|E|C|D]+)/page(?P<page>\d+)/$', LeaveApplicationListView.as_view(), 
        name='leave_application_list_f_p'),
    url('^larequest/page(?P<page>\d+)/$', LeaveApplicationListView.as_view(),
        name='leave_application_list_p'),    
    url('^lapplication/(?P<pk>\d+)/$', LeaveApplicationDetail.as_view(),
        name='leave_application_detail'),   

    url('^lonleave/(?P<search>\w+)/(?P<show_form>\w+)/$', OnLeaveReportView.as_view(), 
        name='leave_report_on_leave'),
#    url('^lonleave/(?P<search>)/$', OnLeaveReportView.as_view(), 
#        name='leave_report_on_leave'),
    url('^lonleave/(?P<cat>[P|A|E|C|D]+)/page(?P<page>\d+)/$', OnLeaveReportView.as_view(), 
        name='leave_report_on_leave_p'),
    url('^lonleave/pdf/$', OnLeavePdfReportView.as_view(), 
        name='leave_report_on_leave_pdf'),
    url('^leave/detail/(?P<pk>\d+)/$', LeaveRequestDetailView.as_view(), 
        name='leave_request_detail'),
    url('^leave/detail/pdf/(?P<pk>\d+)/$', LeaveRequestPdfDetailView.as_view(), 
        name='leave_request_detail_pdf'),

    url('^ldays/(?P<search>\w+)/(?P<show_form>\w+)/$', EmployeeLeaveDaysReport.as_view(), 
        name='leave_report_days'),
    url('^ldays/pdf/$', EmployeeLeaveDaysPdfView.as_view(), 
        name='leave_days_pdf'),
        
]

leave/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User, Permission
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.shortcuts import reverse

#from notify.signals import notify
import notify
from django_permanent.models import PermanentModel
from django_permanent.query import PermanentQuerySet, NonDeletedQuerySet
from django_permanent.managers import MultiPassThroughManager
#from notify.signals import notify

from payroll.models import EmployeeProfile, ServiceLine, Position

from decimal import Decimal

class Holiday(PermanentModel):
    name = models.CharField(max_length=64)
    date = models.DateField()
    recurring = models.BooleanField(default=True,
        help_text="The day is a holiday every year.")

    def __str__(self):
        return self.name

class LeavePeriod(PermanentModel):
    start_date = models.DateField()
    end_date = models.DateField()
    comment = models.TextField()

    def __str__(self):
        return "{} to {}".format(self.start_date, self.end_date)

def all_positions():
    return Position.objects.all()

def all_service_lines():
    return ServiceLine.objects.all()

class UserLeaveTypeQuerySet(PermanentQuerySet):
    def user_types(self, user=None, **kwargs):

        profile = user.profile
        q=self.filter(
                active=True,
                gender__in=['A', profile.gender],
                removed=None
            )
        exclude_types = []

        for type in q:
            if profile.service_line not in type.service_lines.all():
                exclude_types.append(type)
            if profile.position not in type.positions.all():
                exclude_types.append(type)

        q = q.exclude(pk__in=[type.pk for type in exclude_types])
        return q
UserLeaveTypeManager = UserLeaveTypeQuerySet.as_manager

class UserLeaveTypeManagerOld(models.Manager):
    def get_for_user(self, user_profile):
        exclude_types = []
        q = super(UserLeaveTypeManager, self).get_queryset().filter(
            active=True,
            gender__in=['A', user_profile.gender],
            removed=None
        )

        for type in q:
            if user_profile.service_line not in type.service_lines.all():
                exclude_types.append(type)
            if user_profile.position not in type.positions.all():
                exclude_types.append(type)

        return q.exclude(pk__in=[type.pk for type in exclude_types])

class LeaveType(PermanentModel):

    STATUS_CHOICES = ((0, 'Active'), (1, 'Inactive'))
    GENDER_CHOICES = (('A', 'Any'), ('M', 'Male'), ('F', 'Female'))

    class Meta:
        ordering = ('name', )

    name = models.CharField(max_length=64)
    no_of_days = models.DecimalField(max_digits=4, decimal_places=1, default=0,
        help_text="Maximum number of leave days within a leave period.")
    days_carried_forward = models.DecimalField(max_digits=4,
        decimal_places=1, default=0,
        help_text="If days from the previous leave periods are carried over, "
        "enter maximum number or percentage. 0 for None.")
    active = models.BooleanField(default=True)
    service_lines = models.ManyToManyField(ServiceLine,
        default=all_service_lines)
    positions = models.ManyToManyField(Position, default=all_positions)
    gender = models.CharField(max_length=2, choices=GENDER_CHOICES,
        blank=True, default='A')
    pay_percentage = models.DecimalField(max_digits=4,
        decimal_places=1, default=Decimal('100'))
    description = models.TextField(blank=True)

    objects = MultiPassThroughManager(UserLeaveTypeQuerySet, NonDeletedQuerySet)
#    objects = models.Manager()

    def __str__(self):
        return self.name

    def get_days_carried_forward(self, **kwargs):
        days = self.days_carried_forward
        if days == 0:
            return 0

        try:
            previous_period = LeavePeriod.objects.order_by('-id')[1]
        except:
            return 0
        else:
            bal = self.count_no_of_days_left(profile=kwargs.get('profile'),
                leave_period=previous_period)
            return days if days > bal else bal

    def count_no_of_days_left(self, **kwargs):

        requests = self.leave_requests.filter(
            profile=kwargs.get('profile'))
        leave_period_id = kwargs.get('leave_period_id')
        if leave_period_id:
            requests = requests.filter(leave_period_id=leave_period_id)
        else:
            leave_periods = LeavePeriod.objects.order_by('-id')
            if leave_periods:
                requests = requests.filter(leave_period=leave_periods[0])

        total = 0
        for r in requests:
            if r.is_past_due() is False and r.get_status() in ['P', 'A']:
                total += r.get_no_of_days()
        return self.no_of_days - total

class LeaveApprover(PermanentModel):
    profile = models.ForeignKey(EmployeeProfile, related_name="leave_approvers")

class LeaveRequestManager(models.Manager):
    def get_approvers(self):
        perm = Permission.objects.get(codename='hrp_handle_leave_requests')
        approvers = User.objects.filter(
            models.Q(models.Q(groups__permissions=perm)|
            models.Q(user_permissions=perm)),
            profile__isnull=False
        ).distinct()
        approver_profiles = list(EmployeeProfile.objects.filter(
            user__in=approvers))
        return approver_profiles


    def all_pending(self, **kwargs):

        apps=LeaveApplicationReview.objects.filter(leave_status='P',
            reviewer__in=[r.profile for r in LeaveApprover.objects.all()])
#            reviewer__in=self.get_approvers())
        q = super(LeaveRequestManager, self).get_queryset().filter(
            messages__in=apps)
        return q

    def all_accepted(self, **kwargs):

        reviews=LeaveApplicationReview.objects.filter(
            leave_status='A',
            reviewer__in=[r.profile for r in LeaveApprover.objects.all()])
#            reviewer__in=self.get_approvers())
        q = super(LeaveRequestManager, self).get_queryset().filter(
            messages__in=reviews)

        if kwargs.get('profile'):
            q = q.filter(profile=kwargs.get('profile'))

        return q

    def count_no_of_days_left(self, **kwargs):
        reviews=LeaveApplicationReview.objects.filter(leave_status__in=['P', 'A'],
#            reviewer__in=[r.profile for r in LeaveApprover.objects.all()])
            reviewer__in=self.get_approvers())
        leave_type = kwargs.get('leave_type')
        q = super(LeaveRequestManager, self).get_queryset().filter(
            profile=kwargs.get('profile'),
            leave_type=leave_type,
            messages__in=reviews
        )
        s=s
        total = 0
        for r in q:
            total += r.get_no_of_days()
        return leave_type.no_of_days - total

    def count_no_of_days_left_old(self, **kwargs):
        leave_type = kwargs.get('leave_type')
        q = super(LeaveRequestManager, self).get_queryset().filter(
            profile=kwargs.get('profile'),
            leave_type=leave_type

        )
        total = 0
        for r in q:
            if r.is_past_due() is False and r.get_status in ['P', 'A']:
                total += r.get_no_of_days()
        return leave_type.no_of_days - total

class LeaveRequest(PermanentModel):
    profile = models.ForeignKey(EmployeeProfile,
        related_name="leave_requests")
    leave_period = models.ForeignKey(LeavePeriod, related_name="leave_requests")
    leave_type = models.ForeignKey(LeaveType, related_name="leave_requests")
    start_date = models.DateField()
    end_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    comment = models.TextField()
    no_of_days = models.DecimalField(max_digits=3, decimal_places=1,
        null=True, blank=True)
#    status = models.ForeignKey(LeaveRequestStatus, related_name="request")
    objects = LeaveRequestManager()

    def __str__(self):
        return "{}: {} to {}".format(self.leave_type, self.start_date,
            self.end_date)

    def get_approvers(self):
#        approvers = [r.profile for r in LeaveApprover.objects.all()]
        perm = Permission.objects.get(codename='hrp_handle_leave_requests')
        approvers = User.objects.filter(
            models.Q(models.Q(groups__permissions=perm)|
            models.Q(user_permissions=perm)),
            profile__isnull=False
        ).distinct()
        approver_profiles = list(EmployeeProfile.objects.filter(
            user__in=approvers))
        if self.profile.reports_to:
            approver_profiles.append(self.profile.reports_to)
        return set(approver_profiles)

    def is_past_due(self):
        if self.start_date < timezone.now().date():
            return True
        return False

    def get_status(self):
        '''Returns the latest review from any of the allowed leave approvers'''
        reviews=self.messages.filter(
#            reviewer__in=[r.profile for r in LeaveApprover.objects.all()]
            reviewer__in=self.get_approvers()
            ).order_by('id')
        review = 'P'
        for r in reviews:
            if r.leave_status != 'P':
                return r.leave_status

        if self.is_past_due():
            review = 'E' # Expired without
        return review

    def get_status_display(self):
        '''Returns the latest review from any of the allowed leave approvers'''
        reviews=self.messages.filter(
#            reviewer__in=[r.profile for r in LeaveApprover.objects.all()]
            reviewer__in=self.get_approvers()
            ).order_by('id')
        review = 'Pending'
        for r in reviews:
            if r.leave_status != 'P':
                return r.get_leave_status_display()

        if self.is_past_due():
            review = 'Expired' # Expired without review

        return review

    def get_no_of_days(self):

leave/templates/leave/holiday_confirm_delete.html
{% extends "payroll_base_site.html" %}
{% load i18n %}

{% block main_content %}

<div id="main_panel_container" class="section">
    <h3 class="ico_mug">{% trans 'Administration' %} &rang; {% trans 'Leave' %} &rang; {% trans 'Holidays' %} &rang; {% trans 'Confirm Deletion' %}</h3>

<form action="" method="post">
    {% csrf_token %}
    <div align="center" id="warning">
        <span class="ico_error">
        {% blocktrans %}Are you sure you want to delete <strong>{{ object }}</strong>?{% endblocktrans %}
        </span>
    </div>
    <div align="center">
        <input type="submit" value="{% trans 'Delete' %}" />
        &nbsp;&nbsp;<a href="{% url 'leave:holiday_list' %}">{% trans 'Cancel' %}</a>
    </div>
</form>


</div>
{% endblock main_content %}

leave/templates/leave/holiday_list.html
{% extends "payroll_base_site.html" %}
{% load i18n %}
{% load staticfiles %}

{% block main_content %}



<div id="dashboard" class="left">
    <h4 class="ico_mug">{% trans 'Administration' %} &rang; {% trans 'Leave' %} &rang; {% trans 'Holidays' %}</h4>
    
    {% include 'payroll/databox_notifications.html' with messages=messages%}
    
    <table id="table">

        {% if holiday_list %}
        <tr>
            <th width="10%">#</th>
            <th width="">{% trans 'Name' %}</th>
            <th width="">{% trans 'Date' %}</th>
            <th width="">{% trans 'Recurring' %}</th>
            <th width="20%">{% trans 'Action' %}</th>
        </tr>
        {% endif %}
        {% for holiday in holiday_list %}

        <tr>
            <td>{{  page_obj.start_index|add:forloop.counter0 }}.</td>
            <td>{{ holiday.name }}</td>
            <td>{{ holiday.date }}</td>
            <td>{{ holiday.recurring }}</td>
            <td align="center">
                <a href="{% url 'leave:holiday_edit' pk=holiday.id %}">edit</a>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <a href="{% url 'leave:holiday_delete' pk=holiday.id %}">delete</a>
            </td>
        </tr>
        {% empty %}
        <div id="warning">
            <span class="ico_error">
            {% trans "There are no holidays defined. Click the ADD HOLIDAY button below to create one, e.g. Chrismas" %}
            </span>
        </div>
        {% endfor %}
    </table>

    {% if is_paginated %}
        {% url 'leave:holiday_list' as url %}
        {% include "payroll/pagination_digg.html" with paginator=paginator url=url %}
    {% endif %}
    <div class="blankline"></div>
    <div><a href="{% url 'leave:holiday_create' %}"><button>{% trans 'Add Holiday' %}</button></a></div>
</div>

{% block sidebar %}
{% include 'leave/sidebar.html' with url="holiday_list" menu="setup" %}
{% endblock sidebar %}

{% endblock %}

leave/templates/leave/leave_period_confirm_delete.html
{% extends "payroll_base_site.html" %}
{% load i18n %}

{% block main_content %}

<div id="main_panel_container" class="section">
    <h4 class="ico_mug">Administration &rang; {% trans 'Leave' %} &rang; Leave Periods &rang; {% trans 'Confirm Delete' %}</h4>

<form action="" method="post">
    {% csrf_token %}
    <div align="center" id="warning">
        <span class="ico_error">
        {% blocktrans %}Please confirm deletion of <strong>{{ object.comment }}, </strong>?{% endblocktrans %}<br/>
        </span>
    </div>
    
        <div align='center'>
    <input type="submit" value="Delete" />
    &nbsp;&nbsp;<a href="{% url 'leave:leave_period_list' %}">{% trans 'Cancel' %}</a>
        </div>
</form>


</div>
{% endblock main_content %}

leave/templates/leave/leave_request_form.html
{% extends "payroll_base_site.html" %}
{% load i18n %}
{% load staticfiles %}
{% load humanize %}

{% block extra_scripts %}
    <script type="text/javascript">
        jQuery(function() {
           jQuery("#id_start_date").datepicker({ 
               dateFormat: 'yy-mm-dd',
               minDate: "-0D", maxDate: "+365D"
           });
           jQuery("#id_end_date").datepicker({ 
               dateFormat: 'yy-mm-dd',
               minDate: "-0D", maxDate: "+365D"
           });

        });
    </script>
{% endblock %}
{% block main_content %}

<div id="dashboard" class="left">

    {% trans "Leave" as mod %}
    {% if form.instance.id %}{% trans "Edit" as action %}{% else %}{% trans "New" as action %}{% endif %} 
    {% blocktrans asvar title %}{{ action }} Leave Request{% endblocktrans %}
    <h4 class="ico_mug">{% trans 'Leave' %} &rang; My Requests &rang; {{ action }} Request</h4>
    {% include "payroll/form_error_display.html" with module=mod title=title %}

    <form action="" method="post">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        <fieldset>
            <legend><span>{% trans 'Leave Request' %}</span></legend>
        <table width="100%">

            <tr>
               <td style="vertical-align: top" width="20%"><label for="id_leave_period">{% trans 'Leave Period' %}</label></td>
               <td>
                   <div class="left">
                       {{ form.leave_period }} &nbsp;&nbsp;
                    </div>
                    {% if form.leave_period.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.leave_period.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>
            <tr>
               <td style="vertical-align: top" width="20%"><label for="id_leave_type">{% trans 'Leave Type' %}</label></td>
               <td>
                   <div class="left">
                       {{ form.leave_type }} &nbsp;&nbsp;
                    </div>
                    {% if form.leave_type.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.leave_type.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>
            <tr>
               <td style="vertical-align: top" width="20%"><label for="id_start_date">{% trans 'Start Date' %}</label></td>
               <td>
                    <div class="left">
                       {{ form.start_date }} &nbsp;&nbsp;
                    </div>
                    {% if form.start_date.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.start_date.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>
            <tr>
               <td style="vertical-align: top" width="20%"><label for="id_end_date">{% trans 'End Date' %}</label></td>
               <td>
                    <div class="left">
                       {{ form.end_date }} &nbsp;&nbsp;
                    </div>
                    {% if form.end_date.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.end_date.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>
            <tr>
               <td style="vertical-align: top" width="20%"><label for="id_comment">{% trans 'Comment' %}</label></td>
               <td>
                    <div class="left">
                       {{ form.comment }} &nbsp;&nbsp;
                    </div>
                    {% if form.comment.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.comment.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Save" />&nbsp;&nbsp;
                    <a href="{% url 'leave:leave_request_list' %}">Back to List</a>
                </td>
            </tr>

        </table>
        </fieldset>
    </form>

</div>

{% block sidebar %}
{% include 'leave/sidebar.html' with url="leave_request_list" menu="requests" %}
{% endblock sidebar %}

{% endblock %}

leave/templates/leave/leave_type_form.html
{% extends 'payroll_base_site.html' %}
{% load i18n %}

{% block extra_scripts %}
        <script type="text/javascript">
            jQuery(function() {
               jQuery("#id_start_date").datepicker({ 
                   dateFormat: 'yy-mm-dd'
               });
               jQuery("#id_end_date").datepicker({ 
                   dateFormat: 'yy-mm-dd'
               });
               
            });
        </script>
{% endblock %}

{% block main_content %}

<div id="dashboard" class="left">

    {% if form.instance.id %}{% trans "Edit" as action %}{% else %}{% trans "Add" as action %}{% endif %}     
    <h4 class="ico_mug">{% trans 'Administration' %} &rang; {% trans 'Leave' %} &rang; {% blocktrans %}{{ action }} Leave Type{% endblocktrans %}</h4>

    {% include "payroll/form_error_display.html" %}

    <form action="" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><span>{% trans 'Leave Type' %}</span></legend>
        <table width="100%">

            <tr>
               <td style="vertical-align: top" width="20%"><label for="id_name">{% trans 'Name' %}</label></td>
               <td>
                   <div class="left">
                       {{ form.name }} &nbsp;&nbsp;
                   </div>
                   {% if form.name.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.name.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>
            <tr>
               <td style="vertical-align: top" width="20%"><label for="id_no_of_days">{% trans 'Days' %}</label></td>
               <td>
                   <div class="left">
                       {{ form.no_of_days }} &nbsp;&nbsp;
                   </div>
                   {% if form.no_of_days.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.no_of_days.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>
               <td style="vertical-align: top" width="20%"><label for="id_pay_percentage">{% trans 'Pay Percentage' %}</label></td>
               <td>
                   <div class="left">
                       {{ form.pay_percentage }} &nbsp;&nbsp;
                   </div>
                   {% if form.pay_percentage.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.pay_percentage.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>
            <tr>
               <td style="vertical-align: top" width="20%"><label for="id_days_carried_forward">{% trans 'Days C/f' %}</label></td>
               <td>
                   <div class="left">
                       {{ form.days_carried_forward }} &nbsp;&nbsp;
                   </div>
                   {% if form.days_carried_forward.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.days_carried_forward.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>
            <tr>
               <td style="vertical-align: top" width="20%"><label for="id_active">{% trans 'Active' %}</label></td>
               <td>
                   <div class="left">
                       {{ form.active }} &nbsp;&nbsp;
                   </div>
                   {% if form.active.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.active.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>
            <tr>
               <td style="vertical-align: top" width="20%"><label for="id_service_lines">{% trans 'Service Line' %}</label></td>
               <td>
                   <div class="left">
                       {{ form.service_lines }} &nbsp;&nbsp;
                   </div>
                   {% if form.service_lines.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.service_lines.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>
            <tr>
               <td style="vertical-align: top" width="20%"><label for="id_positions">{% trans 'Positions' %}</label></td>
               <td>
                   <div class="left">
                       {{ form.positions }} &nbsp;&nbsp;
                   </div>
                   {% if form.positions.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.positions.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>
            <tr>
               <td style="vertical-align: top" width="20%"><label for="id_gender">{% trans 'Gender' %}</label></td>
               <td>
                   <div class="left">
                       {{ form.gender }} &nbsp;&nbsp;
                   </div>
                   {% if form.gender.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.gender.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>
            <tr>
               <td style="vertical-align: top" width="20%"><label for="id_description">{% trans 'Description' %}</label></td>
               <td>
                   <div class="left">
                       {{ form.description }} &nbsp;&nbsp;
                   </div>
                   {% if form.description.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.description.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>

            <tr>
                <td></td>
                <td>    <input type="submit" value="Save" /></td>
            </tr>

        </table>
        </fieldset>
    </form>
    <a href="{% url 'leave:leave_type_list' %}"><button>{% trans 'Back' %}</button></a>

</div>

{% block sidebar %}
{% include 'leave/sidebar.html' with url="leave_type_list" menu="setup" %}
{% endblock sidebar %}

{% endblock main_content %}

leave/templates/leave/pagination_digg.html
<div class="pagination">
    
    {% if paginator.has_previous %}
    <a href="{{ url }}page{{ paginator.previous_page_number }}">previous</a>
    {% endif %}

    {% for page in paginator.page_range %}
        {% if not page %}
        ...
        {% else %}
            {% if page == paginator.number %}
                Page {{ page }}
            {% else %}
                <a href="{{ url }}page{{ page }}">{{ page }}</a>
            {% endif %}
        {% endif %}
    {% endfor %}
    
    {% if paginator.has_next %}
        <a href="{{ url }}page{{ paginator.next_page_number }}">next</a>
    {% endif %}
</div>