asset/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [

    url('^$', AssetListView.as_view(), name='asset_list'),
    url('^page(?P<page>\d+)/$', AssetListView.as_view(),
        name='asset_list_p'),    
    url('^new/$', AssetCreateView.as_view(), 
        name='asset_create'),
    url('^asset/edit/(?P<pk>\d+)/$', AssetUpdateView.as_view(), 
        name='asset_edit'),
    url('^asset/delete/(?P<pk>\d+)/$', AssetDeleteView.as_view(), 
        name='asset_delete'),

    url('^allocation/$', AssetIssuanceListView.as_view(), 
        name='asset_allocation_list'),
    url('^allocation/page(?P<page>\d+)/$', AssetIssuanceListView.as_view(),
        name='asset_allocation_list_p'),    
    url('^allocation/(?P<show_asset_search_form>\w+)/(?P<search_data>\w+)/page(?P<page>\d+)/$', 
        AssetIssuanceListView.as_view(),
        name='asset_allocation_list_s'),    
    url('^allocation/new/(?P<asset_id>\d+)/$', AssetIssuanceFormView.as_view(), 
        name='asset_allocation_add'),
    url('^allocation/update/(?P<pk>\d+)/$', AssetReturnFormView.as_view(), 
        name='asset_return'),
        
]

hrp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#import notify
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^leave/', include('leave.urls', namespace='leave')),
    url(r'^appraisal/', include('appraisal.urls', namespace='appraisal')),
    url(r'^recruitment/', include('recruitment.urls', namespace='recruitment')),
    url(r'^asset/', include('asset.urls', namespace='asset')),
    url(r'session_security/', include('session_security.urls')),
#    url(r"^notifications/", include("pinax.notifications.urls",
#        namespace="pinax_notifications")),
    url(r'^notifications/', include('notify.urls', 'notifications')),
    url(r'^', include('payroll.urls', namespace='payroll')),
]

asset/models.py
from __future__ import unicode_literals

from django_permanent.models import PermanentModel
from django.db import models
from django.contrib.auth.models import User

class IdType(PermanentModel):
    class Permanent:
        restore_on_create = True
    description = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.description

class AssetStatus(PermanentModel):
    description = models.CharField(max_length=64)

    def __str__(self):
        return self.description

class Category(PermanentModel):
    class Meta:
        verbose_name_plural = "Categories"
    class Permanent:
        restore_on_create = True

    name = models.CharField(max_length=32, unique=True)
    description = models.CharField(max_length=256, null=True, blank=True)

    def __str__(self):
        return self.name

class Asset(PermanentModel):
    category = models.ForeignKey(Category, related_name='assets')
    model = models.CharField(max_length=32)
    id_type = models.ForeignKey(IdType)
    id_number = models.CharField(max_length=32)
    date_of_manufacture = models.DateTimeField(null=True, blank=True)
    description = models.CharField(max_length=256, null=True)

    def get_current_issue(self):
        try:
            return self.issues.filter(returned_date__isnull=True)[0]
        except:
            return None

    def get_id(self):
        return "{}/{}".format(self.id_type, self.id_number)

    def __str__(self):
        return "{} {}".format(self.category.name, self.get_id())
    
class AssetIssuance(PermanentModel):

    asset = models.ForeignKey(Asset, related_name='issues')
    employee = models.ForeignKey(User, null=True)
    assignment_date = models.DateTimeField(auto_now_add=True)
    returned_date = models.DateTimeField(null=True)
    comment = models.TextField()
    asset_status = models.ForeignKey(AssetStatus, related_name='issues',
        default=1)

leave/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User, Permission
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.shortcuts import reverse

#from notify.signals import notify
import notify
from django_permanent.models import PermanentModel
from django_permanent.query import PermanentQuerySet, NonDeletedQuerySet
from django_permanent.managers import MultiPassThroughManager
#from notify.signals import notify

from payroll.models import EmployeeProfile, ServiceLine, Position

from decimal import Decimal

class Holiday(PermanentModel):
    name = models.CharField(max_length=64)
    date = models.DateField()
    recurring = models.BooleanField(default=True,
        help_text="The day is a holiday every year.")

    def __str__(self):
        return self.name

class LeavePeriod(PermanentModel):
    start_date = models.DateField()
    end_date = models.DateField()
    comment = models.TextField()

    def __str__(self):
        return "{} to {}".format(self.start_date, self.end_date)

def all_positions():
    return Position.objects.all()

def all_service_lines():
    return ServiceLine.objects.all()

class UserLeaveTypeQuerySet(PermanentQuerySet):
    def user_types(self, user=None, **kwargs):

        profile = user.profile
        q=self.filter(
                active=True,
                gender__in=['A', profile.gender],
                removed=None
            )
        exclude_types = []

        for type in q:
            if profile.service_line not in type.service_lines.all():
                exclude_types.append(type)
            if profile.position not in type.positions.all():
                exclude_types.append(type)

        q = q.exclude(pk__in=[type.pk for type in exclude_types])
        return q
UserLeaveTypeManager = UserLeaveTypeQuerySet.as_manager

class UserLeaveTypeManagerOld(models.Manager):
    def get_for_user(self, user_profile):
        exclude_types = []
        q = super(UserLeaveTypeManager, self).get_queryset().filter(
            active=True,
            gender__in=['A', user_profile.gender],
            removed=None
        )

        for type in q:
            if user_profile.service_line not in type.service_lines.all():
                exclude_types.append(type)
            if user_profile.position not in type.positions.all():
                exclude_types.append(type)

        return q.exclude(pk__in=[type.pk for type in exclude_types])

class LeaveType(PermanentModel):

    STATUS_CHOICES = ((0, 'Active'), (1, 'Inactive'))
    GENDER_CHOICES = (('A', 'Any'), ('M', 'Male'), ('F', 'Female'))

    class Meta:
        ordering = ('name', )

    name = models.CharField(max_length=64)
    no_of_days = models.DecimalField(max_digits=4, decimal_places=1, default=0,
        help_text="Maximum number of leave days within a leave period.")
    days_carried_forward = models.DecimalField(max_digits=4,
        decimal_places=1, default=0,
        help_text="If days from the previous leave periods are carried over, "
        "enter maximum number or percentage. 0 for None.")
    active = models.BooleanField(default=True)
    service_lines = models.ManyToManyField(ServiceLine,
        default=all_service_lines)
    positions = models.ManyToManyField(Position, default=all_positions)
    gender = models.CharField(max_length=2, choices=GENDER_CHOICES,
        blank=True, default='A')
    pay_percentage = models.DecimalField(max_digits=4,
        decimal_places=1, default=Decimal('100'))
    description = models.TextField(blank=True)

    objects = MultiPassThroughManager(UserLeaveTypeQuerySet, NonDeletedQuerySet)
#    objects = models.Manager()

    def __str__(self):
        return self.name

    def get_days_carried_forward(self, **kwargs):
        days = self.days_carried_forward
        if days == 0:
            return 0

        try:
            previous_period = LeavePeriod.objects.order_by('-id')[1]
        except:
            return 0
        else:
            bal = self.count_no_of_days_left(profile=kwargs.get('profile'),
                leave_period=previous_period)
            return days if days > bal else bal

    def count_no_of_days_left(self, **kwargs):

        requests = self.leave_requests.filter(
            profile=kwargs.get('profile'))
        leave_period_id = kwargs.get('leave_period_id')
        if leave_period_id:
            requests = requests.filter(leave_period_id=leave_period_id)
        else:
            leave_periods = LeavePeriod.objects.order_by('-id')
            if leave_periods:
                requests = requests.filter(leave_period=leave_periods[0])

        total = 0
        for r in requests:
            if r.is_past_due() is False and r.get_status() in ['P', 'A']:
                total += r.get_no_of_days()
        return self.no_of_days - total

class LeaveApprover(PermanentModel):
    profile = models.ForeignKey(EmployeeProfile, related_name="leave_approvers")

class LeaveRequestManager(models.Manager):
    def get_approvers(self):
        perm = Permission.objects.get(codename='hrp_handle_leave_requests')
        approvers = User.objects.filter(
            models.Q(models.Q(groups__permissions=perm)|
            models.Q(user_permissions=perm)),
            profile__isnull=False
        ).distinct()
        approver_profiles = list(EmployeeProfile.objects.filter(
            user__in=approvers))
        return approver_profiles


    def all_pending(self, **kwargs):

        apps=LeaveApplicationReview.objects.filter(leave_status='P',
            reviewer__in=[r.profile for r in LeaveApprover.objects.all()])
#            reviewer__in=self.get_approvers())
        q = super(LeaveRequestManager, self).get_queryset().filter(
            messages__in=apps)
        return q

    def all_accepted(self, **kwargs):

        reviews=LeaveApplicationReview.objects.filter(
            leave_status='A',
            reviewer__in=[r.profile for r in LeaveApprover.objects.all()])
#            reviewer__in=self.get_approvers())
        q = super(LeaveRequestManager, self).get_queryset().filter(
            messages__in=reviews)

        if kwargs.get('profile'):
            q = q.filter(profile=kwargs.get('profile'))

        return q

    def count_no_of_days_left(self, **kwargs):
        reviews=LeaveApplicationReview.objects.filter(leave_status__in=['P', 'A'],
#            reviewer__in=[r.profile for r in LeaveApprover.objects.all()])
            reviewer__in=self.get_approvers())
        leave_type = kwargs.get('leave_type')
        q = super(LeaveRequestManager, self).get_queryset().filter(
            profile=kwargs.get('profile'),
            leave_type=leave_type,
            messages__in=reviews
        )
        s=s
        total = 0
        for r in q:
            total += r.get_no_of_days()
        return leave_type.no_of_days - total

    def count_no_of_days_left_old(self, **kwargs):
        leave_type = kwargs.get('leave_type')
        q = super(LeaveRequestManager, self).get_queryset().filter(
            profile=kwargs.get('profile'),
            leave_type=leave_type

        )
        total = 0
        for r in q:
            if r.is_past_due() is False and r.get_status in ['P', 'A']:
                total += r.get_no_of_days()
        return leave_type.no_of_days - total

class LeaveRequest(PermanentModel):
    profile = models.ForeignKey(EmployeeProfile,
        related_name="leave_requests")
    leave_period = models.ForeignKey(LeavePeriod, related_name="leave_requests")
    leave_type = models.ForeignKey(LeaveType, related_name="leave_requests")
    start_date = models.DateField()
    end_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    comment = models.TextField()
    no_of_days = models.DecimalField(max_digits=3, decimal_places=1,
        null=True, blank=True)
#    status = models.ForeignKey(LeaveRequestStatus, related_name="request")
    objects = LeaveRequestManager()

    def __str__(self):
        return "{}: {} to {}".format(self.leave_type, self.start_date,
            self.end_date)

    def get_approvers(self):
#        approvers = [r.profile for r in LeaveApprover.objects.all()]
        perm = Permission.objects.get(codename='hrp_handle_leave_requests')
        approvers = User.objects.filter(
            models.Q(models.Q(groups__permissions=perm)|
            models.Q(user_permissions=perm)),
            profile__isnull=False
        ).distinct()
        approver_profiles = list(EmployeeProfile.objects.filter(
            user__in=approvers))
        if self.profile.reports_to:
            approver_profiles.append(self.profile.reports_to)
        return set(approver_profiles)

    def is_past_due(self):
        if self.start_date < timezone.now().date():
            return True
        return False

    def get_status(self):
        '''Returns the latest review from any of the allowed leave approvers'''
        reviews=self.messages.filter(
#            reviewer__in=[r.profile for r in LeaveApprover.objects.all()]
            reviewer__in=self.get_approvers()
            ).order_by('id')
        review = 'P'
        for r in reviews:
            if r.leave_status != 'P':
                return r.leave_status

        if self.is_past_due():
            review = 'E' # Expired without
        return review

    def get_status_display(self):
        '''Returns the latest review from any of the allowed leave approvers'''
        reviews=self.messages.filter(
#            reviewer__in=[r.profile for r in LeaveApprover.objects.all()]
            reviewer__in=self.get_approvers()
            ).order_by('id')
        review = 'Pending'
        for r in reviews:
            if r.leave_status != 'P':
                return r.get_leave_status_display()

        if self.is_past_due():
            review = 'Expired' # Expired without review

        return review

    def get_no_of_days(self):

asset/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import *
    
class UserModelChoiceField(forms.ModelChoiceField):
    
    def __init__(self, queryset=None, empty_label=None, required=True):
        
        super(UserModelChoiceField, self).__init__(queryset=User.objects.none())
        self.queryset = User.objects.filter(profile__isnull=False)
        self.empty_label = empty_label
        self.required = required
        
    def label_from_instance(self, obj):
        return obj.profile.get_fullname()

class AssetIssuanceSearchForm(forms.Form):
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(), 
        empty_label='-- All --',
        required=False)
    employee = UserModelChoiceField(
        empty_label='-- All --',
        required=False)
    issue_status = forms.ChoiceField(
        choices=(
            (0, '-- Any --'), 
            (1, 'Issued'), 
            (2, 'Available')
            )
        )
class AssetIssuanceForm(forms.ModelForm):
    class Meta:
        model = AssetIssuance
        exclude = ('returned_date', 'return_comment')
        widgets = {
            'asset': forms.HiddenInput()
        }
    employee = UserModelChoiceField()
    
class AssetReturnForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AssetReturnForm, self).__init__(*args, **kwargs)
        self.fields['returned_date'].widget = forms.HiddenInput()
        self.fields['asset'].widget = forms.HiddenInput()
        self.fields['returned_date'].widget = forms.HiddenInput()
        
    class Meta:
        model = AssetIssuance
        exclude = ()
        widgets = {
#            'return_date': forms.HiddenInput(),
            'return_comment': forms.Textarea(attrs={'cols': 30, 'rows': 4}),
            'asset': forms.HiddenInput(),
            'employee': forms.HiddenInput(),
        }
        
class AssetAllocationFormOld(forms.Form):
    def __init__(self, *args, **kwargs):
        cat_id = kwargs.pop('category')
        super(AssetAllocationForm, self).__init__(*args, **kwargs)
        self.fields['asset'].queryset = Asset.objects.filter(
            category__id=cat_id if cat_id else 1)

        q = Category.objects.all()
        self.fields['category'].queryset = q
        self.fields['category'].initial = Category.objects.get(pk=cat_id)
        self.fields['category'].widget.attrs = {
            'onChange': "post({}, {});".format(
                '"/asset/allocation/new/"',
                {'from_post': 1}
            )
        }
        
    category = forms.ModelChoiceField(
        queryset=Category.objects.none(),
        empty_label = None
    )
    asset = forms.ModelChoiceField(
        queryset = Asset.objects.none()
    )
    
    class Media:
        js = ('js/hrp.js', )

asset/templates/asset/asset_confirm_delete.html
{% extends "payroll_base_site.html" %}
{% load i18n %}

{% block main_content %}

<div id="main_panel_container" class="section">
    <h3 class="ico_mug">{% trans 'Confirm Deletion' %}</h3>

<form action="" method="post">
    {% csrf_token %}
    <div align="center" id="warning">
        <span class="ico_error">
        {% blocktrans %}Are you sure you want to delete <strong>{{ object }}</strong>?{% endblocktrans %}
        </span>
    </div>
    <div align='center'>
        <input type="submit" value="Delete" />
        &nbsp;&nbsp;<a href="{% url 'asset:asset_list' %}">{% trans 'Cancel' %}</a>
    </div>
</form>


</div>
{% endblock main_content %}

asset/templates/asset/asset_form.html
{% extends 'payroll_base_site.html' %}
{% load i18n %}

{% block extra_scripts %}
    <script type="text/javascript">
        jQuery(function() {
           jQuery("#id_date_of_manufacture").datepicker({ 
               dateFormat: 'yy-mm-dd',
               changeYear: true,
                changeMonth: true, 
               maxDate: "+0D",
               yearRange: "-50:+0"
           });
        });
    </script>
{% endblock %}

{% block main_content %}

<div id="dashboard" class="left">

    {% if form.instance.id %}{% trans "Edit" as action %}{% else %}{% trans "Add" as action %}{% endif %}     
    <h3 class="ico_mug">{% trans 'Administration' %} &rang; {% trans 'Asset' %} &rang; {% blocktrans %}{{ action }} Asset{% endblocktrans %}</h3>

    {% include "payroll/form_error_display.html" %}

    <form action="" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><span>{% trans 'Asset' %}</span></legend>
        <table width="100%">

            <tr>
               <td style="vertical-align: top" width="20%"><label for="id_date">{% trans 'Category' %}</label></td>
               <td>
                   <div class="left">
                       {{ form.category }} &nbsp;&nbsp;
                   </div>
                   {% if form.category.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.category.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>
            <tr>
               <td style="vertical-align: top" width="20%"><label for="id_serial_no">{% trans 'ID Type' %}</label></td>
               <td>
                   <div class="left">
                       {{ form.id_type }} &nbsp;&nbsp;
                   </div>
                   {% if form.id_type.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.id_type.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>
            <tr>
               <td style="vertical-align: top" width="20%"><label for="id_serial_no">{% trans 'ID Number' %}</label></td>
               <td>
                   <div class="left">
                       {{ form.id_number }} &nbsp;&nbsp;
                   </div>
                   {% if form.id_number.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.id_number.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>
            <tr>
               <td style="vertical-align: top" width="20%"><label for="id_description">{% trans 'Description' %}</label></td>
               <td>
                   <div class="left">
                       {{ form.description }} &nbsp;&nbsp;
                   </div>
                   {% if form.description.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.description.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>
            <tr>
               <td style="vertical-align: top" width="20%"><label for="id_date_of_manufacture">{% trans 'Date Of Manufacture' %}</label></td>
               <td>
                   <div class="left">
                       {{ form.date_of_manufacture }} &nbsp;&nbsp;
                   </div>
                   {% if form.date_of_manufacture.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.date_of_manufacture.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>

            <tr>
                <td></td>
                <td>    <input type="submit" value="Save" /></td>
            </tr>

        </table>
        </fieldset>
    </form>
    <a href="{% url 'asset:asset_list_p' page=1 %}"><button>{% trans 'Back' %}</button></a>

</div>

{% block sidebar %}
{% include 'leave/sidebar.html' with url="educ_level_list" menu="personnel" %}
{% endblock sidebar %}

{% endblock main_content %}

asset/templates/asset/asset_list.html
{% extends "payroll_base_site.html" %}
{% load i18n %}
{% load staticfiles %}

{% block main_content %}

<div id="dashboard" class="left">
    
    <h3 class="ico_mug">{% trans 'Assets' %} &rang; {% trans 'Asset List' %}</h3>
    {% if appraisal_list %}
    <p class="info">List of registered company assets.</p>
    <div class="blankline"></div>
    {% endif %}
    {% include 'payroll/databox_notifications.html' with messages=messages %}
    
    <table id="table">

        {% if asset_list %}
        <tr>
            <th width="10%">#</th>
            <th width="">{% trans 'Category' %}</th>
            <th width="">{% trans 'ID Type' %}</th>
            <th width="">{% trans 'ID No.' %}</th>
            <th width="">{% trans 'Manufactured' %}</th>
            <th width="">{% trans 'Description' %}</th>
            <th width="20%">{% trans 'Action' %}</th>
        </tr>
        {% endif %}
        {% for asset in asset_list %}
        <tr>
            <td>{{  page_obj.start_index|add:forloop.counter0 }}.</td>
            <td>{{ asset.category }}</td>
            <td>{{ asset.id_type }}</td>
            <td>{{ asset.id_number }}</td>
            <td>{{ asset.date_of_manufacture|date }}</td>
            <td>{{ asset.description }}</td>
            <td align="center">
                <a href="{% url 'asset:asset_edit' pk=asset.id %}">{% trans 'edit' %}</a>
                &nbsp;&nbsp;
                <a href="{% url 'asset:asset_delete' pk=asset.id %}">{% trans 'delete' %}</a>
            </td>
        </tr>
        {% empty %}
        <div id="warning">
            <span class="ico_error">
            {% trans "Register a new asset by clicking the ADD ASSET button below." %}
            </span>
        </div>
        {% endfor %}
    </table>

    {% if is_paginated %}
        {% url 'asset:asset_list' as url %}
        {% include "payroll/pagination_digg.html" with paginator=paginator url=url %}
    {% endif %}
    <div class="blankline"></div>
    <div><a href="{% url 'asset:asset_create' %}"><button>{% trans 'ADD ASSET' %}</button></a></div>
</div>

{% block sidebar %}
{% include 'leave/sidebar.html' with url="holiday_list" menu="setup" %}
{% endblock sidebar %}

{% endblock %}

asset/templates/asset/assetissuance_form.html
{% extends 'payroll_base_site.html' %}
{% load i18n %}

{% block extra_css %}
<style>
    .td {padding-bottom: 8px}
</style>
{% endblock %}

{% block main_content %}

<div id="dashboard" class="left">

    <h3 class="ico_mug">{% trans 'Asset' %} &rang; {% if form.instance.id %} Return {% else %}Allocate {% endif %}Asset</h3>
    {% include "payroll/form_error_display.html" %}
    <form action="" method="post" id="allocation_form">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        <fieldset>
            <legend><span>{% trans 'Asset' %}</span></legend>
        <table width="100%">

            <tr>
               <td style="padding-bottom: 8px">{% trans 'Asset' %}</td>
               <td>{{ asset.category }}</td>
            </tr>
            <tr>
               <td style="padding-bottom: 8px">{% trans 'Model' %}</td>
               <td>{{ asset.model }}</td>
            </tr>
            <tr>
               <td style="padding-bottom: 8px">{% trans 'ID No.' %}</td>
               <td>{{ asset.get_id }}</td>
            </tr>
            {% if not form.instance.id %}
            <tr>
               <td style="vertical-align: top; padding-bottom: 8px" width="20%"><label for="id_category">{% trans 'Employee' %}</label></td>
               <td>
                   <div class="left">
                       {{ form.employee }} &nbsp;&nbsp;
                   </div>
                   {% if form.employee.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.employee.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            <tr>
            <tr>
               <td style="vertical-align: top; padding-bottom: 8px" width="20%"><label for="status">{% trans 'Asset Status' %}</label></td>
               <td>
                   <div class="left">
                       {{ form.asset_status }} &nbsp;&nbsp;
                   </div>
                   {% if form.asset_status.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.asset_status.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            <tr>
            {% else %}
            <tr>
               <td style="padding-bottom: 8px">{% trans 'Employee' %}</td>
               <td>{{ object.employee.profile.get_fullname }}</td>
            </tr>
            <tr>
               <td style="vertical-align: top; padding-bottom: 8px" width="20%"><label for="status">{% trans 'Asset Status' %}</label></td>
               <td>
                   <div class="left">
                       {{ form.asset_status }} &nbsp;&nbsp;
                   </div>
                   {% if form.asset_status.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.asset_status.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            <tr>
            {% endif %}
            <tr>
               <td style="vertical-align: top; padding-bottom: 8px" width="20%"><label for="status">{% trans 'Comment' %}</label></td>
               <td>
                   <div class="left">
                       {{ form.comment }} &nbsp;&nbsp;
                   </div>
                   {% if form.comment.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.comment.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            <tr>
            <tr>
                <td></td>
                <td>    <input type="submit" value="Save" /></td>
            </tr>

        </table>
        </fieldset>
    </form>
    <a href="{% url 'asset:asset_allocation_list' %}"><button>{% trans 'Back' %}</button></a>

</div>

{% block sidebar %}
{% include 'leave/sidebar.html' with url="educ_level_list" menu="personnel" %}
{% endblock sidebar %}

{% endblock main_content %}

asset/templates/asset/assetissuance_search_form.html
{% load i18n %}
{% if show_search_form == 'on' %}
<div>
    <form action="{% url 'asset:asset_allocation_list' %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><span>{% trans 'Search' %}</span></legend>
        <table width="100%">

            <tr>
               <td style="vertical-align: top" width="20%"><label for="id_date">{% trans 'Category' %}</label></td>
               <td>
                   <div class="left">
                       {{ search_form.category }} &nbsp;&nbsp;
                   </div>
                </td>
            </tr>
            <tr>
               <td style="vertical-align: top" width="20%"><label for="id_employee">{% trans 'Employee' %}</label></td>
               <td>
                   <div class="left">
                       {{ search_form.employee }} &nbsp;&nbsp;
                   </div>
                </td>
            </tr>
            <tr>
               <td style="vertical-align: top" width="20%"><label for="id_date">{% trans 'Allocation Status' %}</label></td>
               <td>
                   <div class="left">
                       {{ search_form.issue_status }} &nbsp;&nbsp;
                   </div>
                </td>
            </tr>

            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Search" />&nbsp;&nbsp;
                    {% if search_form.is_bound %}
                    <a href="{% url 'asset:asset_allocation_list_s' page=1 show_asset_search_form='on' search_data='off' %}">Reset</a>
                    {% endif %}
                </td>
            </tr>

        </table>
        </fieldset>
    </form>
</div>
<div>
    <a href="{% url 'asset:asset_allocation_list_s' page=1 show_asset_search_form='off' search_data='off' %}"><button>Hide Search Form</button></a>
</div>
{% else %}
<div>
    <a href="{% url 'asset:asset_allocation_list_s' page=1 show_asset_search_form='on' search_data='off' %}"><button>Show Search Form</button></a>
</div>
{% endif %}