appraisal/urls.py
from django.conf.urls import url
from appraisal.views import *

urlpatterns = [

    url('^appraisal/$', AppraisalListView.as_view(), name='appraisal_list'),
    url('^appraisal/page(?P<page>\d+)/$', AppraisalListView.as_view(),
        name='appraisal_list_p'),    
    url('^lappraisal/new/$', AppraisalCreateView.as_view(), 
        name='appraisal_create'),
    url('^appraisal/edit/(?P<pk>\d+)/$', AppraisalUpdateView.as_view(), 
        name='appraisal_edit'),
    url('^appraisal/delete/(?P<pk>\d+)/$', AppraisalDeleteView.as_view(), 
        name='appraisal_delete'),

    url('^appraisalparam/$', AppraisalParameterListView.as_view(), 
        name='appraisal_parameter_list'),
    url('^appraisalparam/page(?P<page>\d+)/$', 
        AppraisalParameterListView.as_view(), 
        name='appraisal_parameter_list_p'),    
    url('^lappraisalparam/new/$', AppraisalParameterCreateView.as_view(), 
        name='appraisal_parameter_create'),
    url('^appraisalparam/edit/(?P<pk>\d+)/$',
        AppraisalParameterUpdateView.as_view(), 
        name='appraisal_parameter_edit'),
    url('^appraisalparam/delete/(?P<pk>\d+)/$', 
        AppraisalParameterDeleteView.as_view(), 
        name='appraisal_parameter_delete'),

    url('^appraisal/measure/$', AppraisalMeasureListView.as_view(), 
        name='appraisal_measure_list'),
    url('^appraisal/measure/page(?P<page>\d+)/$', 
        AppraisalMeasureListView.as_view(), 
        name='appraisal_measure_list_p'),    
    url('^lappraisal/measure/new/$', AppraisalMeasureCreateView.as_view(), 
        name='appraisal_measure_create'),
    url('^appraisal/measure/edit/(?P<pk>\d+)/$',
        AppraisalMeasureUpdateView.as_view(), 
        name='appraisal_measure_edit'),
    url('^appraisal/measure/delete/(?P<pk>\d+)/$', 
        AppraisalMeasureDeleteView.as_view(), 
        name='appraisal_measure_delete'),

    url('^empappraisal/$', EmployeeAppraisalListView.as_view(), 
        name='employee_appraisal_list'),
    url('^empappraisal/page(?P<page>\d+)/$', 
        EmployeeAppraisalListView.as_view(), 
        name='employee_appraisal_list_p'),
    url('^empappraisalms/(?P<emp_app_id>\d+)/$', 
        EmployeeAppraisalMeasureView.as_view(), 
        name='employee_appraisal_measure_list'),
    url('^empappraisalmspdf/(?P<emp_app_id>\d+)/$', 
        EmployeeAppraisalMeasurePdfView.as_view(), 
        name='employee_appraisal_measure_pdf'),
    url('^empappraisalms/(?P<emp_app_id>\d+)/page(?P<page>\d+)/$', 
        EmployeeAppraisalMeasureView.as_view(), 
        name='employee_appraisal_measure_list_p'),
    url('^lappraisal/empmeasure/update/(?P<pk>\d+)/$', 
        EmployeeAppraisalMeasureUpdateView.as_view(), 
        name='employee_appraisal_measure_update'),
        
    url('^empappraisal/submit/(?P<pk>\d+)/$', AppraisalFlowCreateView.as_view(), 
        name='employee_appraisal_submit'),

    url('^recempappraisal/$', ReceivedEmployeeAppraisalListView.as_view(), 
        name='received_employee_appraisal_list'),
    url('^recempappraisal/page(?P<page>\d+)/$', 
        ReceivedEmployeeAppraisalListView.as_view(), 
        name='received_employee_appraisal_list_p'),
    url('^recempappraisams/(?P<emp_app_id>\d+)/$', 
        ReceivedEmployeeAppraisalMeasureView.as_view(), 
        name='received_employee_appraisal_measure_list'),
    url('^recempappraisams/(?P<emp_app_id>\d+)/page(?P<page>\d+)/$', 
        ReceivedEmployeeAppraisalMeasureView.as_view(), 
        name='received_employee_appraisal_measure_list_p'),
    url('^lappraisal/recempmeasure/update/(?P<pk>\d+)/$', 
        ReceivedAppraisalMeasureUpdateView.as_view(), 
        name='received_appraisal_measure_update'),
        
    url('^reports/performance/$', PreformanceSummaryReport.as_view(), 
        name='performance_summary'),
    url('^reports/performance/(?P<appraisal_id>\d+)/pdf/$', 
        PerformanceSummaryPdfReportView.as_view(), name='performance_summary_pdf'),
    url('^reports/performance/(?P<appraisal_id>\d+)/csv/$', 
        PerformanceSummaryPdfReportView.as_view(), name='performance_summary_csv'),

#    url('^recempappraisal/submit/(?P<pk>\d+)/$', 
#        SupervisorAppraisalMeasureUpdateView.as_view(), 
#        name='supervisor_appraisal_measure_list'),

]

asset/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [

    url('^$', AssetListView.as_view(), name='asset_list'),
    url('^page(?P<page>\d+)/$', AssetListView.as_view(),
        name='asset_list_p'),    
    url('^new/$', AssetCreateView.as_view(), 
        name='asset_create'),
    url('^asset/edit/(?P<pk>\d+)/$', AssetUpdateView.as_view(), 
        name='asset_edit'),
    url('^asset/delete/(?P<pk>\d+)/$', AssetDeleteView.as_view(), 
        name='asset_delete'),

    url('^allocation/$', AssetIssuanceListView.as_view(), 
        name='asset_allocation_list'),
    url('^allocation/page(?P<page>\d+)/$', AssetIssuanceListView.as_view(),
        name='asset_allocation_list_p'),    
    url('^allocation/(?P<show_asset_search_form>\w+)/(?P<search_data>\w+)/page(?P<page>\d+)/$', 
        AssetIssuanceListView.as_view(),
        name='asset_allocation_list_s'),    
    url('^allocation/new/(?P<asset_id>\d+)/$', AssetIssuanceFormView.as_view(), 
        name='asset_allocation_add'),
    url('^allocation/update/(?P<pk>\d+)/$', AssetReturnFormView.as_view(), 
        name='asset_return'),
        
]

hrp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#import notify
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^leave/', include('leave.urls', namespace='leave')),
    url(r'^appraisal/', include('appraisal.urls', namespace='appraisal')),
    url(r'^recruitment/', include('recruitment.urls', namespace='recruitment')),
    url(r'^asset/', include('asset.urls', namespace='asset')),
    url(r'session_security/', include('session_security.urls')),
#    url(r"^notifications/", include("pinax.notifications.urls",
#        namespace="pinax_notifications")),
    url(r'^notifications/', include('notify.urls', 'notifications')),
    url(r'^', include('payroll.urls', namespace='payroll')),
]

leave/urls.py
__author__ = "Steven Kawuma <kawuma@gmail.com>"
__date__ = "Feb 14, 2017 3:06:12 PM"

from django.conf.urls import url
from leave.views import *

urlpatterns = [

    url('^holiday/new/$', HolidayCreateView.as_view(), name='holiday_create'),
    url('^holiday/$', HolidayListView.as_view(), name='holiday_list'),
    url('^holiday/page(?P<page>\d+)/$', HolidayListView.as_view(),
        name='holiday_list_p'),    
    url('^holiday/edit/(?P<pk>\d+)/$', HolidayUpdateView.as_view(), 
        name='holiday_edit'),
    url('^holiday/delete/(?P<pk>\d+)/$', HolidayDeleteView.as_view(), 
        name='holiday_delete'),
        
    url('^lperiod/new/$', LeavePeriodCreateView.as_view(), 
        name='leave_period_create'),
    url('^lperiod/$', LeavePeriodListView.as_view(), name='leave_period_list'),
    url('^lperiod/page(?P<page>\d+)/$', LeavePeriodListView.as_view(),
        name='leave_period_list_p'),    
    url('^lperiod/edit/(?P<pk>\d+)/$', LeavePeriodUpdateView.as_view(), 
        name='leave_period_edit'),
    url('^lperiod/delete/(?P<pk>\d+)/$', LeavePeriodDeleteView.as_view(), 
        name='leave_period_delete'),

    url('^ltype/new/$', LeaveTypeCreateView.as_view(), 
        name='leave_type_create'),
    url('^ltype/$', LeaveTypeListView.as_view(), name='leave_type_list'),
    url('^ltype/page(?P<page>\d+)/$', LeaveTypeListView.as_view(),
        name='leave_type_list_p'),    
    url('^ltype/edit/(?P<pk>\d+)/$', LeaveTypeUpdateView.as_view(), 
        name='leave_type_edit'),
    url('^ltype/delete/(?P<pk>\d+)/$', LeaveTypeDeleteView.as_view(), 
        name='leave_type_delete'),

    url('^lapprover/$', LeaveApproverView.as_view(), name='leave_approvers'),
    url('^lapprover/(?P<rem_pk>\d+)/rem/$', LeaveApproverView.as_view(), 
        name='leave_approver_remove'),

    url('^lrequest/$', LeaveRequestListView.as_view(), 
        name='leave_request_list'),
    url('^lrequest/(?P<cat>[P|A|E|C|D]+)/$', LeaveRequestListView.as_view(), 
        name='leave_request_list_f'),
    url('^lrequest/(?P<cat>[P|A|E|C|D]+)/page(?P<page>\d+)/$', LeaveRequestListView.as_view(), 
        name='leave_request_list_f_p'),
    url('^lrequest/page(?P<page>\d+)/$', LeaveRequestListView.as_view(),
        name='leave_request_list_p'),    
    url('^lrequest/(?P<cancel_pk>\d+)/cancel/$', LeaveRequestListView.as_view(), 
        name='leave_request_cancel'),
    url('^lrequest/new/$', LeaveRequestCreateView.as_view(), 
        name='leave_request_create'),

    url('^larequest/$', LeaveApplicationListView.as_view(), 
        name='leave_application_list'),
    url('^larequest/(?P<cat>[P|A|E|C|D]+)/$', LeaveApplicationListView.as_view(), 
        name='leave_application_list_f'),
    url('^larequest/(?P<cat>[P|A|E|C|D]+)/page(?P<page>\d+)/$', LeaveApplicationListView.as_view(), 
        name='leave_application_list_f_p'),
    url('^larequest/page(?P<page>\d+)/$', LeaveApplicationListView.as_view(),
        name='leave_application_list_p'),    
    url('^lapplication/(?P<pk>\d+)/$', LeaveApplicationDetail.as_view(),
        name='leave_application_detail'),   

    url('^lonleave/(?P<search>\w+)/(?P<show_form>\w+)/$', OnLeaveReportView.as_view(), 
        name='leave_report_on_leave'),
#    url('^lonleave/(?P<search>)/$', OnLeaveReportView.as_view(), 
#        name='leave_report_on_leave'),
    url('^lonleave/(?P<cat>[P|A|E|C|D]+)/page(?P<page>\d+)/$', OnLeaveReportView.as_view(), 
        name='leave_report_on_leave_p'),
    url('^lonleave/pdf/$', OnLeavePdfReportView.as_view(), 
        name='leave_report_on_leave_pdf'),
    url('^leave/detail/(?P<pk>\d+)/$', LeaveRequestDetailView.as_view(), 
        name='leave_request_detail'),
    url('^leave/detail/pdf/(?P<pk>\d+)/$', LeaveRequestPdfDetailView.as_view(), 
        name='leave_request_detail_pdf'),

    url('^ldays/(?P<search>\w+)/(?P<show_form>\w+)/$', EmployeeLeaveDaysReport.as_view(), 
        name='leave_report_days'),
    url('^ldays/pdf/$', EmployeeLeaveDaysPdfView.as_view(), 
        name='leave_days_pdf'),
        
]

recruitment/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from recruitment.views import (
    VacancyCreateView, 
    VacancyListView, 
    VacancyUpdateView, 
    VacancyDetailView, 
    VacancyDeleteView,
    JobApplicationCreateView,
    ExternalJobApplicationCreateView,
    JobApplicationListView, 
    JobApplicationDetailView,
    EvaluationStageView,
    EvaluationStageDeleteView
)

urlpatterns = [

    url('^vac/page(?P<page>\d+)/$', VacancyListView.as_view(), 
        name='vacancy_list'),
    url('^vac/(?P<pk>\d+)/$', VacancyDetailView.as_view(), 
        name='vacancy_detail'),
    url('^vac/new/$', VacancyCreateView.as_view(), name='vacancy_add'),
    url('^vac/edit/(?P<pk>\d+)$', VacancyUpdateView.as_view(), 
        name='vacancy_edit'),
    url('^vac/del/(?P<pk>\d+)$', VacancyDeleteView.as_view(), 
        name='vacancy_delete'),

    url('^eval/(?P<vac_id>\d+)/page(?P<page>\d+)/$', EvaluationStageView.as_view(), 
        name='eval_list'),
    url('^eval/del/(?P<pk>\d+)$', EvaluationStageDeleteView.as_view(), 
        name='eval_delete'),

#    url('^app/page(?P<page>\d+)/$', JobApplicationListView.as_view(), 
#        name='application_list'),
    url('^app/(?P<vac_id>\d+)/page(?P<page>\d+)/$', JobApplicationListView.as_view(), 
        name='application_list'),
    url('^app/(?P<vac_id>\d+)/page(?P<page>\d+)/(?P<search>\w+)/(?P<show_form>\w+)$', JobApplicationListView.as_view(), 
        name='application_list_r'),
    url('^app/new/(?P<vac_id>\d+)/$', JobApplicationCreateView.as_view(), 
        name='application_add'),
    url('^app/new/ext/(?P<vac_id>\d+)/$', csrf_exempt(ExternalJobApplicationCreateView.as_view()), 
        name='application_add_ext'),
    url('^app/detail/(?P<pk>\d+)/$', JobApplicationDetailView.as_view(), 
        name='application_detail'),
        
]

templates/payroll_base_site.html
{% extends 'payroll_base.html' %}
{% load i18n %}
{% load staticfiles %}
{% block body %}
<div  id="header">
    <div id="profile_info">
        <img src="{% static 'img/avatar.jpg' %}" id="avatar" alt="avatar" />
        <p>{% trans "Welcome " %} <strong>{{ user }}</strong>. </p>
        <p>
            <a href="{% url 'payroll:change_password' %}">{% trans "Change Password" %}</a>&nbsp;&nbsp;
            <a href="{% url 'payroll:logout' %}">Log out</a>
        </p>
        <p class="last_login">{% trans "Last login" %}: {{ user.last_login|date:"d/M/Y H:i" }}</p>
    </div>
    <div id="logo"><h1><a href="{% url 'payroll:home' %}">Payroll</a></h1></div>
</div><!-- end header -->

<div id="content" >
{% block menu %}
{% include 'top_menu.html' %}
{% endblock menu %}

<div id="content_main" class="clearfix">

{% block main_content %}{% endblock main_content %}
</div><!-- end #content_main -->

{% block footer %}
<div  id="footer" class="clearfix">
    <p class="left">Human Resource and Payroll</p>
    <p class="right">&copy;&nbsp;{% now "Y" %}</p>
</div><!-- end #footer -->
{% endblock footer %}
</div>

{% endblock body %}

templates/payroll_base_site1.html
{% extends 'payroll_base1.html' %}
{% load i18n %}
{% load staticfiles %}
{% block body %}
<!-- Loader -->
<body>
  <div id="preloader"><div id="status"><div class="spinner"></div></div></div>
  <!--<div id="content_main" class="clearfix" >-->
  <div class="wrapper">
    <div class="container-fluid">
    <!--  {% include 'navbar.html' %}-->

        {% block menu %}
        <div id="content" >
        {% include 'top_menu.html' %}
        </div>
        {% endblock menu %}

      {% block main_content %}{% endblock main_content %}
      <!--</div>--><!-- end #content_main -->
    </div>
  </div>

  <footer class="footer">
      <div class="container-fluid">
          <div class="row">
              <div class="col-12">
                  © {% now "Y" %}
                  <i class="mdi mdi-heart text-danger"></i>
                  Human Resource and Payroll.<br/>

              </div>
          </div>
      </div>
  </footer><!-- end #footer -->


</body>

{% endblock body %}

templates/top_menu.html
{% load i18n %}
{% load humanize %}
{% load notification_tags %}
{% include_notify_js_variables %}

<div id="top_menu" class="clearfix">
    <ul class="sf-menu"> <!-- DROPDOWN MENU -->
        <li class="current"><a href="{% url 'payroll:home' %}">{% trans "Dashboard" %}</a></li>
        {% if perms.payroll.hrp_configure_company or perms.payroll.hrp_configure_pim or perms.payroll.hrp_configure_leave or perms.payroll.hrp_configure_payroll or perms.payroll.hrp_configure_appraisal %}
        <li>
            <a href="#">{% trans "Administration" %}</a>
            <ul>
                {% if perms.payroll.hrp_configure_company %}
                <li>
                    <a href="#">{% trans "Company Info" %}</a>
                    <ul>
                        <li><a href="{% url 'payroll:position_list' %}">{% trans "Positions" %}</a></li>
                        <li><a href="{% url 'payroll:sl_list' %}">{% trans "Service Lines" %}</a></li>
                        <li><a href="{% url 'payroll:sl_type_list' %}">{% trans "Service Line Types" %}</a></li>
                    </ul>
                </li>
                {% endif %}
                {% if perms.payroll.hrp_configure_pim %}
                <li>
                    <a href="#">{% trans "Personnel Info" %}</a>
                    <ul>
                        <li>
                            <a href="#">{% trans "Qualifications" %}</a>
                            <ul>
                                <li class="current"><a href="{% url 'payroll:educ_level_list' %}">{% trans "Education" %}</a></li>
                                <li><a href="{% url 'payroll:cert_list' %}">{% trans "Certification" %}</a></li>
                                <li><a href="{% url 'payroll:skill_list' %}">{% trans "Skills" %}</a></li>
                                <li><a href="{% url 'payroll:membership_list' %}">{% trans "Membership" %}</a></li>
                                <li><a href="{% url 'payroll:lang_list' %}">{% trans "Languages" %}</a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'payroll:nat_list' %}">{% trans "Nationalities" %}</a></li>
                        <li><a href="{% url 'payroll:employeetitle_list' %}">{% trans "Employee Titles" %}</a></li>                        
                    </ul>
                </li>
                {% endif %}
                {% if perms.payroll.hrp_configure_leave %}
                <li>
                    <a href="#">{% trans "Leave Info" %}</a>
                    <ul>
                        <li><a href="{% url 'leave:holiday_list' %}">{% trans "Holidays" %}</a></li>
                        <li><a href="{% url 'leave:leave_period_list' %}">{% trans "Leave Periods" %}</a></li>
                        <li><a href="{% url 'leave:leave_type_list' %}">{% trans "Leave Types" %}</a></li>
                        <li><a href="{% url 'leave:leave_approvers' %}">{% trans "Approvers" %}</a></li>
                    </ul>
                </li>
                {% endif %}
                {% if perms.payroll.hrp_configure_payroll %}
                <li>
                    <a href="#">{% trans "Payroll Setup" %}</a>
                    <ul>
                        <li><a href="{% url 'payroll:bank_list' %}">{% trans "Banks" %}</a></li>
                        <li><a href="{% url 'payroll:allowancetype_list' %}">{% trans "Allowances" %}</a></li>
                        <li><a href="{% url 'payroll:deductiontype_list' %}">{% trans "Deductions" %}</a></li>
                        <li><a href="{% url 'payroll:salary_scale_list' %}">{% trans "Salary Scales" %}</a></li>
                    </ul>
                </li>
                {% endif %}
                {% if perms.asset.change_asset %}
                <li>
                    <a href="{% url 'asset:asset_list' %}">{% trans "Assets" %}</a>
                </li>
                {% endif %}
                {% if perms.payroll.hrp_configure_appraisal %}
                <li>
                    <a href="#">{% trans "Appraisal Setup" %}</a>
                    <ul>
                        <li><a href="{% url 'appraisal:appraisal_parameter_list' %}">{% trans "Parameters" %}</a></li>
                        <li><a href="{% url 'appraisal:appraisal_measure_list' %}">{% trans "Measures" %}</a></li>
                    </ul>
                </li>
                {% endif %}
                {% if perms.payroll.hrp_do_backup %}
                <li><a href="#">{% trans 'Backup' %}</a></li>
                {% endif %}
            </ul>
        </li>
        {% endif %}
        <li>
            <a href="#">{% trans "PIM" %}</a>
            <ul>
                <li><a href="{% url 'payroll:user_list' %}">{% trans "List Staff" %}</a></li>
                <li><a href="{% url 'payroll:user_add' %}">{% trans "Add Staff" %}</a></li>
            </ul>
        </li>
        <li>
            <a href="#">{% trans "Appraisal" %}</a>
            <ul>
                {% if perms.payroll.hrp_manage_appraisals %}
                <li>
                    <a href="{% url 'appraisal:appraisal_list' %}">{% trans "App. Period" %}</a>
                    <ul>
                        <li><a href="{% url 'appraisal:appraisal_create' %}">{% trans "New" %}</a></li>
                        {% if user.profile %}
                        <li><a href="{% url 'appraisal:appraisal_list' %}">{% trans 'List' %}</a></li>
                        {% endif %}
                    </ul>
                </li>
                {% endif %}
                {% if user.profile %}
                <li>
                    <a href="{% url 'appraisal:employee_appraisal_list' %}">{% trans 'Review' %}</a>
                    <ul>
                        <li><a href="{% url 'appraisal:employee_appraisal_list' %}">{% trans 'My Appraisals' %}</a></li>
                        <li><a href="{% url 'appraisal:received_employee_appraisal_list' %}">{% trans 'Received Appraisals' %}</a></li>
                    </ul>
                </li>
                {% endif %}
            </ul>
        </li>
        <li>
            <a href="#">{% trans "Leave" %}</a>
            <ul>
                <li>
                    <a href="#">{% trans "Applications" %}</a>
                    <ul>
                        {% if perms.payroll.hrp_handle_leave_requests %}
                        <li><a href="{% url 'leave:leave_application_list' %}">{% trans "Received" %}</a></li>
                        {% endif %}
                        <li><a href="{% url 'leave:leave_request_list' %}">{% trans "My Requests" %}</a></li>
                    </ul>
                </li>
            </ul>
        </li>
        <li>
            <a href="#">{% trans "Assets" %}</a>
            <ul>
                <li>
                    <a href="{% url 'asset:asset_allocation_list' %}">{% trans "Allocations" %}</a>
                </li>
            </ul>
        </li>
            <li>
                <a href="#">{% trans "Payroll" %}</a>
                <ul>
                    <li><a href="{% url 'payroll:payperiod_list' %}">{% trans "Pay Periods" %}</a></li>
                    <li><a href="{% url 'payroll:emp_adj_list' %}">{% trans "Recurring Adjustments" %}</a></li>
                </ul>
            </li>
            
            <li>
                <a href="#">{% trans "Recruitment" %}</a>
                <ul>
                    <li><a href="{% url 'recruitment:vacancy_list' page=1 %}">{% trans "Vacancies" %}</a></li>
                </ul>
            </li>
            
            <li>
                <a href="#">{% trans "Reports" %}</a>
                <ul>
                    {% if perms.payroll.hrp_manage_payroll or perms.payroll.hrp_view_payroll_reports %}
                    <li>
                        <a href="#">{% trans 'Payroll' %} </a>
                        <ul>
                            <li><a href="{% url 'payroll:payroll_cycles_summary' %}">{% trans "Summary" %}</a></li>
                            <li><a href="{% url 'payroll:bank_report' %}">{% trans "Bank" %}</a></li>
                            <li><a href="{% url 'payroll:payroll_summary_report' %}">{% trans "Service Line" %}</a></li>
                            <li><a href="{% url 'payroll:nssf_report' %}">{% trans "NSSF" %}</a></li>
                            <li><a href="{% url 'payroll:paye_report' %}">{% trans "PAYE" %}</a></li>
                        </ul>
                    </li>
                    {% endif %}
                    <li>
                        <a href="#">{% trans "Leave" %}</a>
                        <ul>
                            <li><a href="{% url 'leave:leave_report_on_leave' search='off' show_form='off' %}">{% trans "On Leave" %}</a></li>
                            <li><a href="{% url 'leave:leave_report_days' search='off' show_form='off' %}">{% trans "Leave Days" %}</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">{% trans "Personnel" %}</a>
                        <ul>
                            <li><a href="{% url 'payroll:user_report' %}">{% trans "Emp. Details" %}</a></li>
                            <li><a href="{% url 'payroll:salary_progression_report' %}">{% trans "Salary History" %}</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">{% trans "Appraisal" %}</a>
                        <ul>
                            <li><a href="{% url 'appraisal:performance_summary' %}">{% trans "Summary Rpt" %}</a></li>
                        </ul>
                    </li>
                    {% if perms.payroll.can_view_system_reports %}
                    <li>
                        <a href="">{% trans 'System' %}</a>
                        <ul>
                            <li><a href="{% url 'payroll:activity_list' %}">{% trans 'User Activity' %}</a></li>
                        </ul>
                    </li>
                    {% endif %}
                </ul>
            </li>
            <li>
                <a href="#">{% trans "Help" %}</a>
            </li>
    </ul>
        <a href="{% url 'payroll:notification_list' %}" id="visit" class="right">
            <em><span id="notifUnreadCount">{{ request.user.notifications.unread.count }}</span> {% trans "Notifications" %}</em></a>

</div>