hrp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#import notify
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^leave/', include('leave.urls', namespace='leave')),
    url(r'^appraisal/', include('appraisal.urls', namespace='appraisal')),
    url(r'^recruitment/', include('recruitment.urls', namespace='recruitment')),
    url(r'^asset/', include('asset.urls', namespace='asset')),
    url(r'session_security/', include('session_security.urls')),
#    url(r"^notifications/", include("pinax.notifications.urls",
#        namespace="pinax_notifications")),
    url(r'^notifications/', include('notify.urls', 'notifications')),
    url(r'^', include('payroll.urls', namespace='payroll')),
]

recruitment/urls.py
from django.conf.urls import url
from django.views.decorators.csrf import csrf_exempt

from recruitment.views import (
    VacancyCreateView, 
    VacancyListView, 
    VacancyUpdateView, 
    VacancyDetailView, 
    VacancyDeleteView,
    JobApplicationCreateView,
    ExternalJobApplicationCreateView,
    JobApplicationListView, 
    JobApplicationDetailView,
    EvaluationStageView,
    EvaluationStageDeleteView
)

urlpatterns = [

    url('^vac/page(?P<page>\d+)/$', VacancyListView.as_view(), 
        name='vacancy_list'),
    url('^vac/(?P<pk>\d+)/$', VacancyDetailView.as_view(), 
        name='vacancy_detail'),
    url('^vac/new/$', VacancyCreateView.as_view(), name='vacancy_add'),
    url('^vac/edit/(?P<pk>\d+)$', VacancyUpdateView.as_view(), 
        name='vacancy_edit'),
    url('^vac/del/(?P<pk>\d+)$', VacancyDeleteView.as_view(), 
        name='vacancy_delete'),

    url('^eval/(?P<vac_id>\d+)/page(?P<page>\d+)/$', EvaluationStageView.as_view(), 
        name='eval_list'),
    url('^eval/del/(?P<pk>\d+)$', EvaluationStageDeleteView.as_view(), 
        name='eval_delete'),

#    url('^app/page(?P<page>\d+)/$', JobApplicationListView.as_view(), 
#        name='application_list'),
    url('^app/(?P<vac_id>\d+)/page(?P<page>\d+)/$', JobApplicationListView.as_view(), 
        name='application_list'),
    url('^app/(?P<vac_id>\d+)/page(?P<page>\d+)/(?P<search>\w+)/(?P<show_form>\w+)$', JobApplicationListView.as_view(), 
        name='application_list_r'),
    url('^app/new/(?P<vac_id>\d+)/$', JobApplicationCreateView.as_view(), 
        name='application_add'),
    url('^app/new/ext/(?P<vac_id>\d+)/$', csrf_exempt(ExternalJobApplicationCreateView.as_view()), 
        name='application_add_ext'),
    url('^app/detail/(?P<pk>\d+)/$', JobApplicationDetailView.as_view(), 
        name='application_detail'),
        
]

leave/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User, Permission
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.shortcuts import reverse

#from notify.signals import notify
import notify
from django_permanent.models import PermanentModel
from django_permanent.query import PermanentQuerySet, NonDeletedQuerySet
from django_permanent.managers import MultiPassThroughManager
#from notify.signals import notify

from payroll.models import EmployeeProfile, ServiceLine, Position

from decimal import Decimal

class Holiday(PermanentModel):
    name = models.CharField(max_length=64)
    date = models.DateField()
    recurring = models.BooleanField(default=True,
        help_text="The day is a holiday every year.")

    def __str__(self):
        return self.name

class LeavePeriod(PermanentModel):
    start_date = models.DateField()
    end_date = models.DateField()
    comment = models.TextField()

    def __str__(self):
        return "{} to {}".format(self.start_date, self.end_date)

def all_positions():
    return Position.objects.all()

def all_service_lines():
    return ServiceLine.objects.all()

class UserLeaveTypeQuerySet(PermanentQuerySet):
    def user_types(self, user=None, **kwargs):

        profile = user.profile
        q=self.filter(
                active=True,
                gender__in=['A', profile.gender],
                removed=None
            )
        exclude_types = []

        for type in q:
            if profile.service_line not in type.service_lines.all():
                exclude_types.append(type)
            if profile.position not in type.positions.all():
                exclude_types.append(type)

        q = q.exclude(pk__in=[type.pk for type in exclude_types])
        return q
UserLeaveTypeManager = UserLeaveTypeQuerySet.as_manager

class UserLeaveTypeManagerOld(models.Manager):
    def get_for_user(self, user_profile):
        exclude_types = []
        q = super(UserLeaveTypeManager, self).get_queryset().filter(
            active=True,
            gender__in=['A', user_profile.gender],
            removed=None
        )

        for type in q:
            if user_profile.service_line not in type.service_lines.all():
                exclude_types.append(type)
            if user_profile.position not in type.positions.all():
                exclude_types.append(type)

        return q.exclude(pk__in=[type.pk for type in exclude_types])

class LeaveType(PermanentModel):

    STATUS_CHOICES = ((0, 'Active'), (1, 'Inactive'))
    GENDER_CHOICES = (('A', 'Any'), ('M', 'Male'), ('F', 'Female'))

    class Meta:
        ordering = ('name', )

    name = models.CharField(max_length=64)
    no_of_days = models.DecimalField(max_digits=4, decimal_places=1, default=0,
        help_text="Maximum number of leave days within a leave period.")
    days_carried_forward = models.DecimalField(max_digits=4,
        decimal_places=1, default=0,
        help_text="If days from the previous leave periods are carried over, "
        "enter maximum number or percentage. 0 for None.")
    active = models.BooleanField(default=True)
    service_lines = models.ManyToManyField(ServiceLine,
        default=all_service_lines)
    positions = models.ManyToManyField(Position, default=all_positions)
    gender = models.CharField(max_length=2, choices=GENDER_CHOICES,
        blank=True, default='A')
    pay_percentage = models.DecimalField(max_digits=4,
        decimal_places=1, default=Decimal('100'))
    description = models.TextField(blank=True)

    objects = MultiPassThroughManager(UserLeaveTypeQuerySet, NonDeletedQuerySet)
#    objects = models.Manager()

    def __str__(self):
        return self.name

    def get_days_carried_forward(self, **kwargs):
        days = self.days_carried_forward
        if days == 0:
            return 0

        try:
            previous_period = LeavePeriod.objects.order_by('-id')[1]
        except:
            return 0
        else:
            bal = self.count_no_of_days_left(profile=kwargs.get('profile'),
                leave_period=previous_period)
            return days if days > bal else bal

    def count_no_of_days_left(self, **kwargs):

        requests = self.leave_requests.filter(
            profile=kwargs.get('profile'))
        leave_period_id = kwargs.get('leave_period_id')
        if leave_period_id:
            requests = requests.filter(leave_period_id=leave_period_id)
        else:
            leave_periods = LeavePeriod.objects.order_by('-id')
            if leave_periods:
                requests = requests.filter(leave_period=leave_periods[0])

        total = 0
        for r in requests:
            if r.is_past_due() is False and r.get_status() in ['P', 'A']:
                total += r.get_no_of_days()
        return self.no_of_days - total

class LeaveApprover(PermanentModel):
    profile = models.ForeignKey(EmployeeProfile, related_name="leave_approvers")

class LeaveRequestManager(models.Manager):
    def get_approvers(self):
        perm = Permission.objects.get(codename='hrp_handle_leave_requests')
        approvers = User.objects.filter(
            models.Q(models.Q(groups__permissions=perm)|
            models.Q(user_permissions=perm)),
            profile__isnull=False
        ).distinct()
        approver_profiles = list(EmployeeProfile.objects.filter(
            user__in=approvers))
        return approver_profiles


    def all_pending(self, **kwargs):

        apps=LeaveApplicationReview.objects.filter(leave_status='P',
            reviewer__in=[r.profile for r in LeaveApprover.objects.all()])
#            reviewer__in=self.get_approvers())
        q = super(LeaveRequestManager, self).get_queryset().filter(
            messages__in=apps)
        return q

    def all_accepted(self, **kwargs):

        reviews=LeaveApplicationReview.objects.filter(
            leave_status='A',
            reviewer__in=[r.profile for r in LeaveApprover.objects.all()])
#            reviewer__in=self.get_approvers())
        q = super(LeaveRequestManager, self).get_queryset().filter(
            messages__in=reviews)

        if kwargs.get('profile'):
            q = q.filter(profile=kwargs.get('profile'))

        return q

    def count_no_of_days_left(self, **kwargs):
        reviews=LeaveApplicationReview.objects.filter(leave_status__in=['P', 'A'],
#            reviewer__in=[r.profile for r in LeaveApprover.objects.all()])
            reviewer__in=self.get_approvers())
        leave_type = kwargs.get('leave_type')
        q = super(LeaveRequestManager, self).get_queryset().filter(
            profile=kwargs.get('profile'),
            leave_type=leave_type,
            messages__in=reviews
        )
        s=s
        total = 0
        for r in q:
            total += r.get_no_of_days()
        return leave_type.no_of_days - total

    def count_no_of_days_left_old(self, **kwargs):
        leave_type = kwargs.get('leave_type')
        q = super(LeaveRequestManager, self).get_queryset().filter(
            profile=kwargs.get('profile'),
            leave_type=leave_type

        )
        total = 0
        for r in q:
            if r.is_past_due() is False and r.get_status in ['P', 'A']:
                total += r.get_no_of_days()
        return leave_type.no_of_days - total

class LeaveRequest(PermanentModel):
    profile = models.ForeignKey(EmployeeProfile,
        related_name="leave_requests")
    leave_period = models.ForeignKey(LeavePeriod, related_name="leave_requests")
    leave_type = models.ForeignKey(LeaveType, related_name="leave_requests")
    start_date = models.DateField()
    end_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    comment = models.TextField()
    no_of_days = models.DecimalField(max_digits=3, decimal_places=1,
        null=True, blank=True)
#    status = models.ForeignKey(LeaveRequestStatus, related_name="request")
    objects = LeaveRequestManager()

    def __str__(self):
        return "{}: {} to {}".format(self.leave_type, self.start_date,
            self.end_date)

    def get_approvers(self):
#        approvers = [r.profile for r in LeaveApprover.objects.all()]
        perm = Permission.objects.get(codename='hrp_handle_leave_requests')
        approvers = User.objects.filter(
            models.Q(models.Q(groups__permissions=perm)|
            models.Q(user_permissions=perm)),
            profile__isnull=False
        ).distinct()
        approver_profiles = list(EmployeeProfile.objects.filter(
            user__in=approvers))
        if self.profile.reports_to:
            approver_profiles.append(self.profile.reports_to)
        return set(approver_profiles)

    def is_past_due(self):
        if self.start_date < timezone.now().date():
            return True
        return False

    def get_status(self):
        '''Returns the latest review from any of the allowed leave approvers'''
        reviews=self.messages.filter(
#            reviewer__in=[r.profile for r in LeaveApprover.objects.all()]
            reviewer__in=self.get_approvers()
            ).order_by('id')
        review = 'P'
        for r in reviews:
            if r.leave_status != 'P':
                return r.leave_status

        if self.is_past_due():
            review = 'E' # Expired without
        return review

    def get_status_display(self):
        '''Returns the latest review from any of the allowed leave approvers'''
        reviews=self.messages.filter(
#            reviewer__in=[r.profile for r in LeaveApprover.objects.all()]
            reviewer__in=self.get_approvers()
            ).order_by('id')
        review = 'Pending'
        for r in reviews:
            if r.leave_status != 'P':
                return r.get_leave_status_display()

        if self.is_past_due():
            review = 'Expired' # Expired without review

        return review

    def get_no_of_days(self):

recruitment/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

from payroll.models.employee_models import (ServiceLine, Position,
    EducationLevel, EmployeeProfile)

GENDER_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female')
)

class District(models.Model):
    short_name = models.CharField(max_length=4)
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name

class Vacancy(models.Model):
    VACANCY_TYPE_CHOICES = (
        ('PUB', 'Public'),
        ('INT', 'Internal'),
    )
    GENDER_CHOICES = (
        ('A', 'Any'), ('M', 'Male'), ('F', 'Female')
    )

    class Meta:
        ordering = ['-due_date']

    job_title = models.ForeignKey(Position, related_name='vacancies')
    service_line = models.ForeignKey(ServiceLine, null=True, blank=True)
    reports_to = models.ForeignKey(Position, null=True, blank=True)
    due_date = models.DateField()
    minimum_education = models.CharField(max_length=16,
        choices=EducationLevel.EDUC_LEVEL_CHOICES, null=True, blank=True)
    fields_of_education = models.TextField(null=True,
        blank=True, help_text="Separate with semi-colon (;)")
    skills = models.TextField(max_length=256, null=True, blank=True)
    number_of_positions = models.IntegerField(default=1)
    job_description = models.TextField()
    vacancy_type = models.CharField(max_length=8, choices=VACANCY_TYPE_CHOICES,
        default=VACANCY_TYPE_CHOICES[0][1])
    duty_station = models.ForeignKey(District, null=True, blank=True)
    min_age = models.IntegerField(null=True, blank=True)
    max_age = models.IntegerField(null=True, blank=True)
    experience_years = models.IntegerField(null=True, blank=True)
    required_gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='M')

    def __str__(self):
        return self.job_title.name

class EvaluationStage(models.Model):
    STATUS_CHOICES = (('OPEN', 'Open'), ('CLOSED', 'Closed'))
    class Meta:
        unique_together = ('vacancy', 'name')

    vacancy = models.ForeignKey(Vacancy, related_name='evaluation_stages')
    name = models.CharField(max_length=32)
    description = models.CharField(max_length=64)
    status = models.CharField(max_length=8, choices=STATUS_CHOICES,
        default=STATUS_CHOICES[0][0], blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(EmployeeProfile)

    def __str__(self):
        return self.name

class JobApplication(models.Model):
    APPLICATION_SOURCE_CHOICES = (
        ('NP', 'Newspaper'),
        ('REF', 'Referral'),
        ('WEB', 'Website')
    )
    QUALIFICATION_CHOICES = (
        ('PRIM', 'Primary Level'),
        ('OLEV', 'Secondary Level'),
        ('ALEV', 'Advanced Level'),
        ('DEG', 'Bachelors Degree'),
        ('DIPL', 'Diploma'),
        ('MAST', 'Masters Degree'),
        ('PHD', 'Phd'),
    )

    class Meta:
        ordering = ['-id']

    employee = models.ForeignKey(EmployeeProfile,
        related_name="job_applications", null=True, blank=True)
    vacancy = models.ForeignKey(Vacancy, related_name='applications')
    first_name = models.CharField(max_length=32)
    surname = models.CharField(max_length=32)
    other_names = models.CharField(max_length=64, null=True, blank=True)
    date_of_birth = models.DateField()
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='M')
#    source = models.CharField(max_length=16, choices=APPLICATION_SOURCE_CHOICES,
#        default='NP')
    email = models.EmailField()
    tel_number = models.CharField(max_length=16)
    qualification = models.CharField(max_length=16,
        choices=QUALIFICATION_CHOICES, null=True, blank=True)
    experience_years = models.DecimalField(decimal_places=1, max_digits=3)
    education_fields = models.TextField()
    remarks = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    evaluation_stage = models.ForeignKey(EvaluationStage, null=True, blank=True)

    @property
    def age_of_applicant(self):
        td = timezone.now().date() - self.date_of_birth
        return int(td.days/365.2425)

    def get_fullname(self):
        return "{} {} {}".format(
            self.surname,
            self.first_name if self.first_name else '',
            self.other_names if self.other_names else ''
        )

def upload_directory(instance, filename):
    return 'payroll/static/uploads/{}/{}'.format(
        'recruitment', filename)

class JobApplicationDocument(models.Model):
    job_application = models.ForeignKey(JobApplication,
        related_name='documents')
    document = models.FileField(upload_to=upload_directory, #'uploads/recrutment/%Y/%m/%d/',
        null=True, blank=True)
    description = models.CharField(max_length=32, blank=True)

    def filename(self):
        import os
        return os.path.basename(self.document.name)

recruitment/templates/recruitment/jobapplication_list.html
{% extends "payroll_base_site.html" %}
{% load i18n %}
{% load staticfiles %}

{% block main_content %}

<div id="dashboard" class="left">

    <h3 class="ico_mug">{% trans 'Recruitment' %} &rang; {% trans 'Applications' %} &rang; {{ vacancy }}</h3>
    {% include 'payroll/databox_notifications.html' with messages=messages%}
    {% if request.session.show_search_form %}
    {% include 'recruitment/jobapplication_list_search_form.html' %}
    {% endif %}
    {% if request.session.show_search_form %}
    <a href="{% url 'recruitment:application_list_r' vac_id=vacancy.id page=1 search='on' show_form='off' %}"><button>Hide search form</button></a>
    {% if form.is_bound %}
    <a href="{% url 'recruitment:application_list_r' vac_id=vacancy.id page=1 search='off' show_form='on'%}"><button>Clear Search</button></a>
    {% endif %}
    {% else %}
    <a href="{% url 'recruitment:application_list_r' vac_id=vacancy.id page=1 search='off' show_form='on' %}"><button>Show search form</button></a>
    {% if form.is_bound %}
    <a href="{% url 'recruitment:application_list_r' vac_id=vacancy.id page=1 search='off' show_form='off'%}"><button>Clear Search</button></a>
    {% endif %}
    {% endif %}
    <table id="table">

        {% if jobapplication_list %}
        <tr>
            <th width="5%">#</th>
            <th width="">{% trans 'Name' %}</th>
            <th width="">{% trans 'Qualification' %}</th>
            <th width="">{% trans 'Gender' %}</th>
            <th width="">{% trans 'Age' %}</th>
            <th width="">{% trans 'Exp.' %} (Yrs)</th>
            <th width="">{% trans 'Stage' %}</th>
            <th >{% trans 'Action' %}</th>
        </tr>
        {% endif %}
        {% for application in jobapplication_list %}

        <tr>
            <td>{{ page_obj.start_index|add:forloop.counter0 }}.</td>
            <td>{{ application.get_fullname }}</td>
            <td>{{ application.get_qualification_display }}</td>
            <td>{{ application.gender }}</td>
            <td>{{ application.age_of_applicant }}</td>
            <td align="right">{{ application.experience_years }}</td>
            <td align="center">{{ application.evaluation_stage }}</td>
            <td align="center">
                <a href="{% url 'recruitment:application_detail' pk=application.id %}">details</a>
            </td>
        </tr>
        {% empty %}
        <div id="warning">
            <span class="ico_error">
            {% trans "No applications found." %}
            </span>
        </div>
        {% endfor %}
    </table>

    {% if is_paginated %}
        {% include "recruitment/pagination_digg.html" with paginator=paginator url=pg_url %}
    {% endif %}
    
    <div class="blankline"></div>
        <div class="blankline"></div>
    {% if perms.payroll.hrp_manage_recruitment %}
    <div><a href="{% url 'recruitment:vacancy_list' page=1 %}"><button>{% trans 'Back' %}</button></a></div>
    {% endif %}

</div>

{% block sidebar %}
{% include 'leave/sidebar.html' with url="holiday_list" menu="setup" %}
{% endblock sidebar %}

{% endblock %}

recruitment/templates/recruitment/jobapplication_list_search_form.html
{% load i18n %}
<form action="{% url 'recruitment:application_list' vac_id=vacancy.id page=1 %}" method="post" enctype="multipart/form-data">
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    {% csrf_token %}
    <fieldset>
        <legend><span>{% trans 'Search' %}</span></legend>
        <table width="100%">
            <tr>
                <td style="vertical-align: top; padding-bottom: 10px;" width="20%">Evaluation Stage</td>
                <td>{{ form.stage }}</td>
            </tr>
            <tr>
                <td style="vertical-align: top; padding-bottom: 10px;" width="20%">Experience Over (Yrs)</td>
                <td>
                    <div>{{ form.experience_years_threshold }}</div>
                    {% if form.experience_years_threshold.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.experience_years_threshold.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td style="vertical-align: top; padding-bottom: 10px;" width="20%">Age Lower Limit (Yrs)</td>
                <td>
                    <div>{{ form.age_lower_limit }}</div>
                    {% if form.age_lower_limit.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.age_lower_limit.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td style="vertical-align: top; padding-bottom: 10px;" width="20%">Age Upper Limit (Yrs)</td>
                <td>
                    <div>{{ form.age_upper_limit }}</div>
                    {% if form.age_upper_limit.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.age_upper_limit.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td style="vertical-align: top; padding-bottom: 10px;" width="20%">Gender</td>
                <td>
                    <div>{{ form.gender }}</div>
                    {% if form.gender.errors %}
                    <div id="fail" class="quickview left"><span class="ico_cancel">{{ form.gender.errors|striptags }}</span></div>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>&nbsp;</td>
                <td>
                    <input type="submit" value="Search" />&nbsp;
                    <a href="{% url 'recruitment:application_list_r' vac_id=vacancy.id page=1 search='off' show_form='on'%}">Reset</a>
                </td>
            </tr>
        </table>
    </fieldset>
</form>

recruitment/templates/recruitment/vacancy_detail.html
{% extends 'payroll_base_site.html' %}
{% load i18n %}

{% block main_content %}
<div id="dashboard" class="left">
    <h3 class="ico_mug">
        {% trans 'Recruitment' %} &rang;
        <a href="{% url 'recruitment:vacancy_list' page=1 %}">Vacancies</a> 
        &nbsp;&rang;&nbsp; {% blocktrans %}Vacancy Details{% endblocktrans %}
    </h3>

    <table id="table" width="100%">
        <tr><th colspan="2">Application Details</th></tr>
        <tr>
            <td style="vertical-align: top" width="30%">Vacancy Type</td>
            <td>{{ vacancy.vacancy_type }}</td>
        </tr>
        <tr>
            <td style="vertical-align: top" width="30%">Job Title</td>
            <td>{{ vacancy.job_title }}</td>
        </tr>
        <tr>
            <td style="vertical-align: top" width="30%">Number of Positions</td>
            <td>{{ vacancy.number_of_positions }}</td>
        </tr>
        <tr>
            <td style="vertical-align: top" width="30%">Service Line</td>
            <td>{{ vacancy.service_line }}</td>
        </tr>
        <tr>
            <td style="vertical-align: top" width="30%">Reports To</td>
            <td>{{ vacancy.reports_to }}</td>
        </tr>
        <tr>
            <td style="vertical-align: top" width="30%">Minimum Education</td>
            <td>{{ vacancy.minimum_education }}</td>
        </tr>
        <tr>
            <td style="vertical-align: top" width="30%">Skills</td>
            <td>{{ vacancy.skills }}</td>
        </tr>
        <tr>
            <td style="vertical-align: top" width="30%">Required Gender</td>
            <td>{{ vacancy.get_required_gender_display }}</td>
        </tr>
        <tr>
            <td style="vertical-align: top" width="30%">Fields of Education</td>
            <td>{{ vacancy.fields_of_education }}</td>
        </tr>
        <tr>
            <td style="vertical-align: top" width="30%">Job Description</td>
            <td>{{ vacancy.job_description }}</td>
        </tr>
        <tr>
            <td style="vertical-align: top" width="30%">Due Date</td>
            <td>{{ vacancy.due_date }}</td>
        </tr>
    </table>
<p>
    <a href="{% url 'recruitment:vacancy_list' page=1 %}"><button>Back to Vacancy List</button></a>&nbsp;
    <a href="{% url 'recruitment:application_add' vac_id=vacancy.id %}"><button>Apply</button></a>&nbsp;
    <a href="{% url 'recruitment:eval_list' vac_id=vacancy.id page=1 %}"><button>Evaluation Stages</button></a>
</p>
</div>
{% block sidebar %}
{% include 'leave/sidebar.html' with url="vacancy_list" menu="setup" %}
{% endblock sidebar %}
        
{% endblock %}

recruitment/templates/recruitment/vacancy_list.html
{% extends "payroll_base_site.html" %}
{% load i18n %}
{% load staticfiles %}

{% block main_content %}

<div id="dashboard" class="left">
    <h3 class="ico_mug">{% trans 'Recruitment' %} &rang; {% trans 'Vacancies' %}</h3>
    
    {% include 'payroll/databox_notifications.html' with messages=messages%}
    
    <table id="table">
        {% if vacancy_list %}
        <tr>
            <th width="5%">#</th>
            <th width="">{% trans 'Job Title' %}</th>
            <th width="">{% trans 'Reports To' %}</th>
            <th width="">{% trans 'No. Positions' %}</th>
            <th width="">{% trans 'No. Applied' %}</th>
            <th width="">{% trans 'Due Date' %}</th>
            <th width="30%">{% trans 'Action' %}</th>
        </tr>
        {% endif %}
        {% for vacancy in vacancy_list %}

        <tr>
            <td>{{  page_obj.start_index|add:forloop.counter0 }}.</td>
            <td>{{ vacancy.job_title }}</td>
            <td>{{ vacancy.reports_to }}</td>
            <td>{{ vacancy.number_of_positions }}</td>
            <td>{{ vacancy.applications.count }}</td>
            <td>{{ vacancy.due_date }}</td>
            <td align="center">
                <a href="{% url 'recruitment:vacancy_detail' pk=vacancy.id %}">details</a>&nbsp;
                <a href="{% url 'recruitment:application_list' page=1 vac_id=vacancy.id %}">applications</a>&nbsp;
                {% if perms.recruitment.change_vacancy %}
                <a href="{% url 'recruitment:vacancy_edit' pk=vacancy.id %}">edit</a>&nbsp;
                <a href="{% url 'recruitment:vacancy_delete' pk=vacancy.id %}">delete</a>
                {% endif %}
            </td>
        </tr>
        {% empty %}
        <div id="warning">
            <span class="ico_error">
            {% trans "There are no openings at the moment." %}
                {% if perms.recruitment.change_vacancy %}Click the CREATE VACANCY button below to create one.{% endif %}
            </span>
        </div>
        {% endfor %}
    </table>

    {% if is_paginated %}
        {% include "recruitment/pagination_digg.html" with paginator=paginator url='/recruitment/vac/' %}
    {% endif %}
    
    <div class="blankline"></div>
    {% if perms.payroll.hrp_manage_recruitment %}
    <div><a href="{% url 'recruitment:vacancy_add' %}"><button>{% trans 'Create Vacancy' %}</button></a></div>
    {% endif %}
</div>

{% block sidebar %}
{% include 'leave/sidebar.html' with url="holiday_list" menu="setup" %}
{% endblock sidebar %}

{% endblock %}